### ISSUE TITLE
KokkosBatched_Gesv_Impl -Werror with gcc/9.1: ‘value.Kokkos::ValLocScalar<double, int>::loc’ may be used uninitialized in this function

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#1771]
Nightly builds with gcc/9.1 are failing with -Werror=maybe-uninitialized:

```
04:07:43 /home/jenkins/jenkins-new/workspace/KokkosKernels_KokkosDev2_GCC91/kokkos-kernels/batched/dense/impl/KokkosBatched_Gesv_Impl.hpp: In static member function ‘static int KokkosBatched::TeamVectorStaticPivoting<MemberType>::invoke(const MemberType&, MatrixType1, MatrixType2, VectorType1, VectorType2, VectorType2, VectorType2, VectorType2) [with MatrixType1 = Kokkos::View<double**, Kokkos::LayoutStride, Kokkos::Device<Kokkos::Threads, Kokkos::HostSpace>, Kokkos::MemoryTraits<0> >; MatrixType2 = Kokkos::View<double**, Kokkos::LayoutRight, Kokkos::Device<Kokkos::Threads, Kokkos::ScratchMemorySpace<Kokkos::Threads> >, Kokkos::MemoryTraits<0> >; VectorType1 = Kokkos::View<double*, Kokkos::LayoutStride, Kokkos::Device<Kokkos::Threads, Kokkos::HostSpace>, Kokkos::MemoryTraits<0> >; VectorType2 = Kokkos::View<double*, Kokkos::LayoutStride, Kokkos::Device<Kokkos::Threads, Kokkos::ScratchMemorySpace<Kokkos::Threads> >, Kokkos::MemoryTraits<0> >; MemberType = Kokkos::Impl::ThreadsExecTeamMember]’:
04:07:43 /home/jenkins/jenkins-new/workspace/KokkosKernels_KokkosDev2_GCC91/kokkos-kernels/batched/dense/impl/KokkosBatched_Gesv_Impl.hpp:304:23: error: ‘value.Kokkos::ValLocScalar<double, int>::loc’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
04:07:43   304 |     row_index = value.loc;
```

This is only occurring with gcc/9.1, not other versions, after one of the following changes:
Git (git https://github.com/kokkos/kokkos.git)

    #6027: replace remaining instances of ALL_t with Kokkos::ALL_t (#6028) ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_KokkosDev2_GCC91/1124/changes#detail))
    Add -Wdeprecated-copy warning and fix OMPT scan bug related to assignment operators (#6026) ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_KokkosDev2_GCC91/1124/changes#detail))

Git (git https://github.com/kokkos/kokkos-kernels.git)

    add ability to generate compile_commands.json for clangd ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_KokkosDev2_GCC91/1124/changes#detail))
    add access to inv permutations to mdf handle ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_KokkosDev2_GCC91/1124/changes#detail))
    Adds team- and thread-based lower-bound and upper-bound search and predicates. ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_KokkosDev2_GCC91/1124/changes#detail))
    accept r-value A matrix ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_KokkosDev2_GCC91/1124/changes#detail))
    #7: (v1): old way for rocsparse and rocblas ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_KokkosDev2_GCC91/1124/changes#detail))
    #7: V2 Added hybrid version for rocblas and rocsparse ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_KokkosDev2_GCC91/1124/changes#detail))
    #7: V3: simplest way to get rocsparse and rocblas ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_KokkosDev2_GCC91/1124/changes#detail))
    #7 Removed V2 and V1. ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_KokkosDev2_GCC91/1124/changes#detail))
    address reviewer comments and run clang-format ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_KokkosDev2_GCC91/1124/changes#detail))
    TPLs: replicating changes made in Trilinos for ROCBLAS/ROCSPARSE ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_KokkosDev2_GCC91/1124/changes#detail))
    docs: Include BatchedGemm ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_KokkosDev2_GCC91/1124/changes#detail))
    .github: Update to actions/checkout@v3 ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_KokkosDev2_GCC91/1124/changes#detail))
    ROCSPARSE: fix unused variable in unit-test ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_KokkosDev2_GCC91/1124/changes#detail))
    clang-format... ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_KokkosDev2_GCC91/1124/changes#detail))

I suspect it may be related to kokkos/kokkos#6026 , but will need to test kokkos-kernels@develop with kokkos versions before/after that change to confirm. Marking as bug and compiler issue for now

**Comment by ndellingwood** [comment]
Resolved by #1778, thanks @lucbv !
