### ISSUE TITLE
CUDA 7.5 (GCC 4.8.4) build errors

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos-kernels#72]
For the version of kokkos-kernels in Trilinos develop as of today, CUDA 7.5 with GCC 4.8.4 reports build errors of the following form on the file `kokkos-kernels/src/common/KokkosKernels_SparseUtils.hpp`:
```
.../Trilinos/packages/kokkos-kernels/src/common/KokkosKernels_SparseUtils.hpp: In function ‘void KokkosKernels::Impl::kk_sort_by_row_size_parallel(lno_t, const size_type*, lno_t*, int, int)’:
.../Trilinos/packages/kokkos-kernels/src/common/KokkosKernels_SparseUtils.hpp:1137:172: error: default arguments are only permitted for function parameters
   Kokkos::parallel_for( my_exec_space(0, nv),
                                                                                                                                                                            ^
```
Errors of this form appear for lines 1137, 1150, 1156, 1162, 1598, 1612, 1656, 1675, 1692, 1761, 1767, 1798, and 1829.

**Comment by mhoemmen** [comment]
I'm not sure what's wrong with this code, btw.  It looks harmless.  I'm using `-std=c++11 -expt-extended-lambda` in my `CMAKE_CXX_FLAGS`, and I've set `Kokkos_ENABLE_Cuda_Lambda:BOOL=ON`.

**Comment by mhoemmen** [comment]
Oddly enough, this works fine with CUDA 8.0 and GCC 5.3.0.

**Comment by ibaned** [comment]
I believe I've seen issues where if a lambda is defined in the body of a function and the function has default arguments, NVCC gets really confused by this. It could be that its a bug that was fixed in CUDA 8.0. The workaround is to refactor the code so that the function containing the lambda doesn't take default arguments.

**Comment by mndevec** [comment]
Thanks @ibaned , I will give that a shot.

**Comment by crtrott** [comment]
That said: Trilinos officially dropped Cuda 7.5 support. KokkosKernels should still support it but not necessarily with Lambdas enabled.

**Comment by crtrott** [comment]
Also: we do not test Cuda 7.5 right now. I will add it later today ...

**Comment by mhoemmen** [comment]
@crtrott wrote:
> Trilinos officially dropped Cuda 7.5 support.

Not until the next minor release, according to this:

https://github.com/trilinos/Trilinos/issues/1278

**Comment by mndevec** [comment]
@mhoemmen 
I have not yet been able to replicate this issue. 

In fact, this code shouldn't be compiled if Cuda is enabled. Are you compiling with NVCC without enabling Cuda?

**Comment by mhoemmen** [comment]
@mndevec wrote:
> In fact, this code shouldn't be compiled if Cuda is enabled. Are you compiling with NVCC without enabling Cuda?

No.  I'll try this again once I get the chance.

**Comment by crtrott** [comment]
I can replicate this issue with CUDA 7.5 using following config:
```
~/Kokkos/kokkos-kernels/scripts/generate_makefile.bash --with-cuda --compiler=/home/crtrott/Kokkos/kokkos/bin/nvcc_wrapper --with-cuda-options=enable_lambda
```

**Comment by mndevec** [comment]
@mhoemmen @crtrott 

Okay, I thanks for the help, I was able to replicate it with enable_lambda option. I will work on this. 
@mhoemmen  : no need to rerun it, sorry about the problem

**Comment by mndevec** [comment]
I was disabling the code that calls the function when cuda is enabled. I am disabling the code now. Hopefully my pull request will fix the problem.
