### ISSUE TITLE
error: no member named 'sort_option' in 'SPADDHandle'

### ISSUE THREAD

**Issue by LutzGross** [kokkos/kokkos-kernels#2347]
compilation of Trilinos 16 (also 15) fails on MacOS with

packages/kokkos-kernels/sparse/src/KokkosSparse_spadd_handle.hpp:113:44: error: no member named 'sort_option' in 'SPADDHandle<lno_row_view_t_, lno_nnz_view_t_, scalar_nnz_view_t_, ExecutionSpace, MemorySpace>'

This under homebrew gcc@14.2.0 , llvm@19.1.0 and

Apple clang version 16.0.0 (clang-1600.0.26.3)
Target: arm64-apple-darwin23.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Installation with [mk_trilinos.sh.gz](https://github.com/user-attachments/files/17156356/mk_trilinos.sh.gz)

**Comment by jrood-nrel** [comment]
I get this error as well. I see it with Trilinos 15.1.1 as well. I can try to build with Spack for 15.1.1 or 16.0.0 and see this error even when it chooses a different Kokkos version for each Trilinos version.

**Comment by jrood-nrel** [comment]
https://github.com/kokkos/kokkos-kernels/pull/2296 solves it. The older versions of kokkos-kernels need to be patched to solve this.

**Comment by lucbv** [comment]
We typically do not patch old version of the code we simply encourage folks to get newer versions with fixes. This would not help with Trilinos unless you build against an external version of Kokkos Kernels. Trilinos could add a patch in Spack for the version affected by this issue?

**Comment by jrood-nrel** [comment]
Yes that is what I am doing.

**Comment by brian-kelley** [comment]
Closing this since it's been fixed in master for several releases.
