### ISSUE TITLE
module load error

### ISSUE THREAD

**Issue by pkuwalter** [kokkos/kokkos-kernels#273]
I used the Redhat 4.4.7-18 with gcc 4.4.7 and CUDA V8.0.61. When I load gcc and cuda compiler, the following problem occurs. How can I sovle this problem?

`[root@node327 modulefiles]$> module load gcc/4.4.7`
`ModuleCmd_Load.c(200):ERROR:105: Unable to locate a modulefile for 'gcc/4.4.7'`
`[root@node327 modulefiles]$> module load cuda/8.0.61`
`ModuleCmd_Load.c(200):ERROR:105: Unable to locate a modulefile for 'cuda/8.0.61'`

**Comment by srajama1** [comment]
This is your machine problem and I suggest contact sysadmins on how to get the right compiler and cuda.

**Comment by mhoemmen** [comment]
kokkos-kernels requires C++11, and thus will not work with GCC 4.4.7.  As far as I know, the oldest supported GCC version is 4.8.4.

**Comment by pkuwalter** [comment]
thanks
