### ISSUE TITLE
`sptrsv` and `spadd` perf_tests don't build on CUDA 12.2.53

### ISSUE THREAD

**Issue by cwpearson** [kokkos/kokkos-kernels#1890]
```
/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_sptrsv_aux.hpp(271): error: identifier "csrsv2Info_t" is undefined
    csrsv2Info_t infoL = 0;
    ^

/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_sptrsv_aux.hpp(272): error: identifier "cusparseCreateCsrsv2Info" is undefined
    status = cusparseCreateCsrsv2Info(&infoL);
             ^

/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_sptrsv_aux.hpp(344): error: identifier "cusparseXcsrsv2_zeroPivot" is undefined
    status = cusparseXcsrsv2_zeroPivot(handle, infoL, &structural_zero);
             ^

/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_sptrsv_aux.hpp(413): error: identifier "csrsv2Info_t" is undefined
    csrsv2Info_t infoU = 0;
    ^

4 errors detected in the compilation of "/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_sptrsv_supernode.cpp".
make[2]: *** [perf_test/sparse/CMakeFiles/sparse_sptrsv_supernode.dir/build.make:76: perf_test/sparse/CMakeFiles/sparse_sptrsv_supernode.dir/KokkosSparse_sptrsv_supernode.cpp.o] Error 2
make[1]: *** [CMakeFiles/Makefile2:2600: perf_test/sparse/CMakeFiles/sparse_sptrsv_supernode.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 87%] Building CXX object graph/unit_test/CMakeFiles/KokkosKernels_graph_serial.dir/backends/Test_Serial_Graph.cpp.o
/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_spadd.cpp(352): error: argument of type "const default_size_type *" is incompatible with parameter of type "const int *"
        KokkosSparse::Impl::cusparse_internal_safe_call(cusparseDcsrgeam2_bufferSizeExt( cusparseHandle, A.numRows(), A.numCols(), &alphabeta, A_cusparse, A.nnz(), A.values.data(), A.graph.row_map.data(), A.graph.entries.data(), &alphabeta, B_cusparse, B.nnz(), B.values.data(), B.graph.row_map.data(), B.graph.entries.data(), C_cusparse, 
                                                                                                                                                                                     ^
          detected during instantiation of "void run_experiment<exec_space>(int, char **, perf_test::CommonInputParams) [with exec_space=Kokkos::Cuda]" at line 93 of /home/groupc/cwpears/kokkos-kernels/perf_test/KokkosKernels_perf_test_instantiation.hpp

/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_spadd.cpp(352): error: argument of type "const default_size_type *" is incompatible with parameter of type "const int *"
        KokkosSparse::Impl::cusparse_internal_safe_call(cusparseDcsrgeam2_bufferSizeExt( cusparseHandle, A.numRows(), A.numCols(), &alphabeta, A_cusparse, A.nnz(), A.values.data(), A.graph.row_map.data(), A.graph.entries.data(), &alphabeta, B_cusparse, B.nnz(), B.values.data(), B.graph.row_map.data(), B.graph.entries.data(), C_cusparse, 
                                                                                                                                                                                                                                                                                       ^
          detected during instantiation of "void run_experiment<exec_space>(int, char **, perf_test::CommonInputParams) [with exec_space=Kokkos::Cuda]" at line 93 of /home/groupc/cwpears/kokkos-kernels/perf_test/KokkosKernels_perf_test_instantiation.hpp

/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_spadd.cpp(352): error: argument of type "default_size_type *" is incompatible with parameter of type "const int *"
       , row_mapC.data(), 
         ^
          detected during instantiation of "void run_experiment<exec_space>(int, char **, perf_test::CommonInputParams) [with exec_space=Kokkos::Cuda]" at line 93 of /home/groupc/cwpears/kokkos-kernels/perf_test/KokkosKernels_perf_test_instantiation.hpp

/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_spadd.cpp(361): error: argument of type "const default_size_type *" is incompatible with parameter of type "const int *"
        KokkosSparse::Impl::cusparse_internal_safe_call(cusparseXcsrgeam2Nnz( cusparseHandle, m, n, A_cusparse, A.nnz(), A.graph.row_map.data(), A.graph.entries.data(), B_cusparse, B.nnz(), B.graph.row_map.data(), B.graph.entries.data(), C_cusparse, row_mapC.data(), &c_nnz, cusparseBuffer), "cusparseXcsrgeam2Nnz( cusparseHandle, m, n, A_cusparse, A.nnz(), A.graph.row_map.data(), A.graph.entries.data(), B_cusparse, B.nnz(), B.graph.row_map.data(), B.graph.entries.data(), C_cusparse, row_mapC.data(), &c_nnz, cusparseBuffer)", "/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_spadd.cpp", 361)
                                                                                                                         ^
          detected during instantiation of "void run_experiment<exec_space>(int, char **, perf_test::CommonInputParams) [with exec_space=Kokkos::Cuda]" at line 93 of /home/groupc/cwpears/kokkos-kernels/perf_test/KokkosKernels_perf_test_instantiation.hpp

/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_spadd.cpp(361): error: argument of type "const default_size_type *" is incompatible with parameter of type "const int *"
        KokkosSparse::Impl::cusparse_internal_safe_call(cusparseXcsrgeam2Nnz( cusparseHandle, m, n, A_cusparse, A.nnz(), A.graph.row_map.data(), A.graph.entries.data(), B_cusparse, B.nnz(), B.graph.row_map.data(), B.graph.entries.data(), C_cusparse, row_mapC.data(), &c_nnz, cusparseBuffer), "cusparseXcsrgeam2Nnz( cusparseHandle, m, n, A_cusparse, A.nnz(), A.graph.row_map.data(), A.graph.entries.data(), B_cusparse, B.nnz(), B.graph.row_map.data(), B.graph.entries.data(), C_cusparse, row_mapC.data(), &c_nnz, cusparseBuffer)", "/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_spadd.cpp", 361)
                                                                                                                                                                                              ^
          detected during instantiation of "void run_experiment<exec_space>(int, char **, perf_test::CommonInputParams) [with exec_space=Kokkos::Cuda]" at line 93 of /home/groupc/cwpears/kokkos-kernels/perf_test/KokkosKernels_perf_test_instantiation.hpp

/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_spadd.cpp(361): error: argument of type "default_size_type *" is incompatible with parameter of type "int *"
        KokkosSparse::Impl::cusparse_internal_safe_call(cusparseXcsrgeam2Nnz( cusparseHandle, m, n, A_cusparse, A.nnz(), A.graph.row_map.data(), A.graph.entries.data(), B_cusparse, B.nnz(), B.graph.row_map.data(), B.graph.entries.data(), C_cusparse, row_mapC.data(), &c_nnz, cusparseBuffer), "cusparseXcsrgeam2Nnz( cusparseHandle, m, n, A_cusparse, A.nnz(), A.graph.row_map.data(), A.graph.entries.data(), B_cusparse, B.nnz(), B.graph.row_map.data(), B.graph.entries.data(), C_cusparse, row_mapC.data(), &c_nnz, cusparseBuffer)", "/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_spadd.cpp", 361)
                                                                                                                                                                                                                                                          ^
          detected during instantiation of "void run_experiment<exec_space>(int, char **, perf_test::CommonInputParams) [with exec_space=Kokkos::Cuda]" at line 93 of /home/groupc/cwpears/kokkos-kernels/perf_test/KokkosKernels_perf_test_instantiation.hpp

/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_spadd.cpp(384): error: argument of type "const default_size_type *" is incompatible with parameter of type "const int *"
          KokkosSparse::Impl::cusparse_internal_safe_call(cusparseDcsrgeam2( cusparseHandle, m, n, &alphabeta, A_cusparse, A.nnz(), A.values.data(), A.graph.row_map.data(), A.graph.entries.data(), &alphabeta, B_cusparse, B.nnz(), B.values.data(), B.graph.row_map.data(), B.graph.entries.data(), C_cusparse, valuesC.data(), row_mapC.data(), entriesC.data(), cusparseBuffer), "cusparseDcsrgeam2( cusparseHandle, m, n, &alphabeta, A_cusparse, A.nnz(), A.values.data(), A.graph.row_map.data(), A.graph.entries.data(), &alphabeta, B_cusparse, B.nnz(), B.values.data(), B.graph.row_map.data(), B.graph.entries.data(), C_cusparse, valuesC.data(), row_mapC.data(), entriesC.data(), cusparseBuffer)", "/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_spadd.cpp", 384)
                                                                                                                                                     ^
          detected during instantiation of "void run_experiment<exec_space>(int, char **, perf_test::CommonInputParams) [with exec_space=Kokkos::Cuda]" at line 93 of /home/groupc/cwpears/kokkos-kernels/perf_test/KokkosKernels_perf_test_instantiation.hpp

/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_spadd.cpp(384): error: argument of type "const default_size_type *" is incompatible with parameter of type "const int *"
          KokkosSparse::Impl::cusparse_internal_safe_call(cusparseDcsrgeam2( cusparseHandle, m, n, &alphabeta, A_cusparse, A.nnz(), A.values.data(), A.graph.row_map.data(), A.graph.entries.data(), &alphabeta, B_cusparse, B.nnz(), B.values.data(), B.graph.row_map.data(), B.graph.entries.data(), C_cusparse, valuesC.data(), row_mapC.data(), entriesC.data(), cusparseBuffer), "cusparseDcsrgeam2( cusparseHandle, m, n, &alphabeta, A_cusparse, A.nnz(), A.values.data(), A.graph.row_map.data(), A.graph.entries.data(), &alphabeta, B_cusparse, B.nnz(), B.values.data(), B.graph.row_map.data(), B.graph.entries.data(), C_cusparse, valuesC.data(), row_mapC.data(), entriesC.data(), cusparseBuffer)", "/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_spadd.cpp", 384)
                                                                                                                                                                                                                                                       ^
          detected during instantiation of "void run_experiment<exec_space>(int, char **, perf_test::CommonInputParams) [with exec_space=Kokkos::Cuda]" at line 93 of /home/groupc/cwpears/kokkos-kernels/perf_test/KokkosKernels_perf_test_instantiation.hpp

/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_spadd.cpp(384): error: argument of type "default_size_type *" is incompatible with parameter of type "int *"
          KokkosSparse::Impl::cusparse_internal_safe_call(cusparseDcsrgeam2( cusparseHandle, m, n, &alphabeta, A_cusparse, A.nnz(), A.values.data(), A.graph.row_map.data(), A.graph.entries.data(), &alphabeta, B_cusparse, B.nnz(), B.values.data(), B.graph.row_map.data(), B.graph.entries.data(), C_cusparse, valuesC.data(), row_mapC.data(), entriesC.data(), cusparseBuffer), "cusparseDcsrgeam2( cusparseHandle, m, n, &alphabeta, A_cusparse, A.nnz(), A.values.data(), A.graph.row_map.data(), A.graph.entries.data(), &alphabeta, B_cusparse, B.nnz(), B.values.data(), B.graph.row_map.data(), B.graph.entries.data(), C_cusparse, valuesC.data(), row_mapC.data(), entriesC.data(), cusparseBuffer)", "/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_spadd.cpp", 384)
                                                                                                                                                                                                                                                                                                                                   ^
          detected during instantiation of "void run_experiment<exec_space>(int, char **, perf_test::CommonInputParams) [with exec_space=Kokkos::Cuda]" at line 93 of /home/groupc/cwpears/kokkos-kernels/perf_test/KokkosKernels_perf_test_instantiation.hpp

/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_spadd.cpp(352): error: argument of type "const default_size_type *" is incompatible with parameter of type "const int *"
        KokkosSparse::Impl::cusparse_internal_safe_call(cusparseDcsrgeam2_bufferSizeExt( cusparseHandle, A.numRows(), A.numCols(), &alphabeta, A_cusparse, A.nnz(), A.values.data(), A.graph.row_map.data(), A.graph.entries.data(), &alphabeta, B_cusparse, B.nnz(), B.values.data(), B.graph.row_map.data(), B.graph.entries.data(), C_cusparse, 
                                                                                                                                                                                     ^
          detected during instantiation of "void run_experiment<exec_space>(int, char **, perf_test::CommonInputParams) [with exec_space=Kokkos::Serial]" at line 127 of /home/groupc/cwpears/kokkos-kernels/perf_test/KokkosKernels_perf_test_instantiation.hpp

/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_spadd.cpp(352): error: argument of type "const default_size_type *" is incompatible with parameter of type "const int *"
        KokkosSparse::Impl::cusparse_internal_safe_call(cusparseDcsrgeam2_bufferSizeExt( cusparseHandle, A.numRows(), A.numCols(), &alphabeta, A_cusparse, A.nnz(), A.values.data(), A.graph.row_map.data(), A.graph.entries.data(), &alphabeta, B_cusparse, B.nnz(), B.values.data(), B.graph.row_map.data(), B.graph.entries.data(), C_cusparse, 
                                                                                                                                                                                                                                                                                       ^
          detected during instantiation of "void run_experiment<exec_space>(int, char **, perf_test::CommonInputParams) [with exec_space=Kokkos::Serial]" at line 127 of /home/groupc/cwpears/kokkos-kernels/perf_test/KokkosKernels_perf_test_instantiation.hpp

/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_spadd.cpp(352): error: argument of type "default_size_type *" is incompatible with parameter of type "const int *"
       , row_mapC.data(), 
         ^
          detected during instantiation of "void run_experiment<exec_space>(int, char **, perf_test::CommonInputParams) [with exec_space=Kokkos::Serial]" at line 127 of /home/groupc/cwpears/kokkos-kernels/perf_test/KokkosKernels_perf_test_instantiation.hpp

/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_spadd.cpp(361): error: argument of type "const default_size_type *" is incompatible with parameter of type "const int *"
        KokkosSparse::Impl::cusparse_internal_safe_call(cusparseXcsrgeam2Nnz( cusparseHandle, m, n, A_cusparse, A.nnz(), A.graph.row_map.data(), A.graph.entries.data(), B_cusparse, B.nnz(), B.graph.row_map.data(), B.graph.entries.data(), C_cusparse, row_mapC.data(), &c_nnz, cusparseBuffer), "cusparseXcsrgeam2Nnz( cusparseHandle, m, n, A_cusparse, A.nnz(), A.graph.row_map.data(), A.graph.entries.data(), B_cusparse, B.nnz(), B.graph.row_map.data(), B.graph.entries.data(), C_cusparse, row_mapC.data(), &c_nnz, cusparseBuffer)", "/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_spadd.cpp", 361)
                                                                                                                         ^
          detected during instantiation of "void run_experiment<exec_space>(int, char **, perf_test::CommonInputParams) [with exec_space=Kokkos::Serial]" at line 127 of /home/groupc/cwpears/kokkos-kernels/perf_test/KokkosKernels_perf_test_instantiation.hpp

/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_spadd.cpp(361): error: argument of type "const default_size_type *" is incompatible with parameter of type "const int *"
        KokkosSparse::Impl::cusparse_internal_safe_call(cusparseXcsrgeam2Nnz( cusparseHandle, m, n, A_cusparse, A.nnz(), A.graph.row_map.data(), A.graph.entries.data(), B_cusparse, B.nnz(), B.graph.row_map.data(), B.graph.entries.data(), C_cusparse, row_mapC.data(), &c_nnz, cusparseBuffer), "cusparseXcsrgeam2Nnz( cusparseHandle, m, n, A_cusparse, A.nnz(), A.graph.row_map.data(), A.graph.entries.data(), B_cusparse, B.nnz(), B.graph.row_map.data(), B.graph.entries.data(), C_cusparse, row_mapC.data(), &c_nnz, cusparseBuffer)", "/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_spadd.cpp", 361)
                                                                                                                                                                                              ^
          detected during instantiation of "void run_experiment<exec_space>(int, char **, perf_test::CommonInputParams) [with exec_space=Kokkos::Serial]" at line 127 of /home/groupc/cwpears/kokkos-kernels/perf_test/KokkosKernels_perf_test_instantiation.hpp

/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_spadd.cpp(361): error: argument of type "default_size_type *" is incompatible with parameter of type "int *"
        KokkosSparse::Impl::cusparse_internal_safe_call(cusparseXcsrgeam2Nnz( cusparseHandle, m, n, A_cusparse, A.nnz(), A.graph.row_map.data(), A.graph.entries.data(), B_cusparse, B.nnz(), B.graph.row_map.data(), B.graph.entries.data(), C_cusparse, row_mapC.data(), &c_nnz, cusparseBuffer), "cusparseXcsrgeam2Nnz( cusparseHandle, m, n, A_cusparse, A.nnz(), A.graph.row_map.data(), A.graph.entries.data(), B_cusparse, B.nnz(), B.graph.row_map.data(), B.graph.entries.data(), C_cusparse, row_mapC.data(), &c_nnz, cusparseBuffer)", "/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_spadd.cpp", 361)
                                                                                                                                                                                                                                                          ^
          detected during instantiation of "void run_experiment<exec_space>(int, char **, perf_test::CommonInputParams) [with exec_space=Kokkos::Serial]" at line 127 of /home/groupc/cwpears/kokkos-kernels/perf_test/KokkosKernels_perf_test_instantiation.hpp

/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_spadd.cpp(384): error: argument of type "const default_size_type *" is incompatible with parameter of type "const int *"
          KokkosSparse::Impl::cusparse_internal_safe_call(cusparseDcsrgeam2( cusparseHandle, m, n, &alphabeta, A_cusparse, A.nnz(), A.values.data(), A.graph.row_map.data(), A.graph.entries.data(), &alphabeta, B_cusparse, B.nnz(), B.values.data(), B.graph.row_map.data(), B.graph.entries.data(), C_cusparse, valuesC.data(), row_mapC.data(), entriesC.data(), cusparseBuffer), "cusparseDcsrgeam2( cusparseHandle, m, n, &alphabeta, A_cusparse, A.nnz(), A.values.data(), A.graph.row_map.data(), A.graph.entries.data(), &alphabeta, B_cusparse, B.nnz(), B.values.data(), B.graph.row_map.data(), B.graph.entries.data(), C_cusparse, valuesC.data(), row_mapC.data(), entriesC.data(), cusparseBuffer)", "/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_spadd.cpp", 384)
                                                                                                                                                     ^
          detected during instantiation of "void run_experiment<exec_space>(int, char **, perf_test::CommonInputParams) [with exec_space=Kokkos::Serial]" at line 127 of /home/groupc/cwpears/kokkos-kernels/perf_test/KokkosKernels_perf_test_instantiation.hpp

/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_spadd.cpp(384): error: argument of type "const default_size_type *" is incompatible with parameter of type "const int *"
          KokkosSparse::Impl::cusparse_internal_safe_call(cusparseDcsrgeam2( cusparseHandle, m, n, &alphabeta, A_cusparse, A.nnz(), A.values.data(), A.graph.row_map.data(), A.graph.entries.data(), &alphabeta, B_cusparse, B.nnz(), B.values.data(), B.graph.row_map.data(), B.graph.entries.data(), C_cusparse, valuesC.data(), row_mapC.data(), entriesC.data(), cusparseBuffer), "cusparseDcsrgeam2( cusparseHandle, m, n, &alphabeta, A_cusparse, A.nnz(), A.values.data(), A.graph.row_map.data(), A.graph.entries.data(), &alphabeta, B_cusparse, B.nnz(), B.values.data(), B.graph.row_map.data(), B.graph.entries.data(), C_cusparse, valuesC.data(), row_mapC.data(), entriesC.data(), cusparseBuffer)", "/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_spadd.cpp", 384)
                                                                                                                                                                                                                                                       ^
          detected during instantiation of "void run_experiment<exec_space>(int, char **, perf_test::CommonInputParams) [with exec_space=Kokkos::Serial]" at line 127 of /home/groupc/cwpears/kokkos-kernels/perf_test/KokkosKernels_perf_test_instantiation.hpp

/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_spadd.cpp(384): error: argument of type "default_size_type *" is incompatible with parameter of type "int *"
          KokkosSparse::Impl::cusparse_internal_safe_call(cusparseDcsrgeam2( cusparseHandle, m, n, &alphabeta, A_cusparse, A.nnz(), A.values.data(), A.graph.row_map.data(), A.graph.entries.data(), &alphabeta, B_cusparse, B.nnz(), B.values.data(), B.graph.row_map.data(), B.graph.entries.data(), C_cusparse, valuesC.data(), row_mapC.data(), entriesC.data(), cusparseBuffer), "cusparseDcsrgeam2( cusparseHandle, m, n, &alphabeta, A_cusparse, A.nnz(), A.values.data(), A.graph.row_map.data(), A.graph.entries.data(), &alphabeta, B_cusparse, B.nnz(), B.values.data(), B.graph.row_map.data(), B.graph.entries.data(), C_cusparse, valuesC.data(), row_mapC.data(), entriesC.data(), cusparseBuffer)", "/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_spadd.cpp", 384)
                                                                                                                                                                                                                                                                                                                                   ^
          detected during instantiation of "void run_experiment<exec_space>(int, char **, perf_test::CommonInputParams) [with exec_space=Kokkos::Serial]" at line 127 of /home/groupc/cwpears/kokkos-kernels/perf_test/KokkosKernels_perf_test_instantiation.hpp

18 errors detected in the compilation of "/home/groupc/cwpears/kokkos-kernels/perf_test/sparse/KokkosSparse_spadd.cpp".
make[2]: *** [perf_test/sparse/CMakeFiles/sparse_spadd.dir/build.make:76: perf_test/sparse/CMakeFiles/sparse_spadd.dir/KokkosSparse_spadd.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2340: perf_test/sparse/CMakeFiles/sparse_spadd.dir/all] Error 2
```

**Comment by brian-kelley** [comment]
#1928 should have fixed the spadd issue, although I didn't see build errors with sptrsv.

**Comment by ndellingwood** [comment]
I think the "raw" CuSparse sptrsv usage in the sptrsv perf test uses the deprecated interface and does not have the updated CuSparse version. If maintaining the raw CuSparse code is no longer necessary the easiest path forward is just to remove it from the perf test (then we don't have to worry about incompatibilities)
