### ISSUE TITLE
Trilinos compilation errors, Cuda builds with UVM: error: static assertion failed with "Incompatible View copy construction" in blas/unit_test/Test_Blas2_syr.hpp(1727)

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#1869]
Trilinos builds with kokkos-kernels' develop branch began failing to compile with merge of #1837 in Cuda builds with UVM enabled

**Compilation error snip**:
```
19:28:38 /home/jenkins/weaver/workspace/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/Trilinos/kokkos/core/src/Kokkos_View.hpp(1319): error: static assertion failed with "Incompatible View copy construction"
19:28:38           detected during:
19:28:38             instantiation of "Kokkos::View<DataType, Properties...>::View(const Kokkos::View<RT, RP...> &, std::enable_if_t<Kokkos::Impl::ViewMapping<Kokkos::View<DataType, Properties...>::traits, Kokkos::View<RT, RP...>::traits, Kokkos::ViewTraits<DataType, Properties...>::specialize>::is_assignable_data_type, void> *) [with DataType=double **, Properties=<std::conditional_t<true, Kokkos::Cuda::array_layout, Kokkos::Cuda::array_layout>, Kokkos::Device<Kokkos::HostSpace::execution_space, Kokkos::Cuda::memory_space>, std::conditional_t<false, void, Kokkos::Experimental::DefaultViewHooks>>, RT=double **, RP=<Kokkos::LayoutLeft, Kokkos::HostSpace>]" 
19:28:38 /home/jenkins/weaver/workspace/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/Trilinos/kokkos-kernels/blas/unit_test/Test_Blas2_syr.hpp(1498): here
19:28:38             instantiation of "void Test::SyrTester<ScalarX, tLayoutX, ScalarA, tLayoutA, Device>::callKkGerAndCompareKkSyrAgainstIt(const ScalarA &, TX &, Test::view_stride_adapter<Test::SyrTester<ScalarX, tLayoutX, ScalarA, tLayoutA, Device>::_ViewTypeA, false> &, const Test::SyrTester<ScalarX, tLayoutX, ScalarA, tLayoutA, Device>::_ViewTypeExpected &, const std::__cxx11::string &) [with ScalarX=double, tLayoutX=Kokkos::LayoutLeft, ScalarA=double, tLayoutA=Kokkos::LayoutLeft, Device=Kokkos::Cuda, TX=Kokkos::View<double *, Kokkos::LayoutLeft, Kokkos::Cuda>]" 
19:28:38 /home/jenkins/weaver/workspace/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/Trilinos/kokkos-kernels/blas/unit_test/Test_Blas2_syr.hpp(324): here
19:28:38             instantiation of "void Test::SyrTester<ScalarX, tLayoutX, ScalarA, tLayoutA, Device>::test(int, int, __nv_bool, __nv_bool, __nv_bool) [with ScalarX=double, tLayoutX=Kokkos::LayoutLeft, ScalarA=double, tLayoutA=Kokkos::LayoutLeft, Device=Kokkos::Cuda]" 
19:28:38 /home/jenkins/weaver/workspace/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/Trilinos/kokkos-kernels/blas/unit_test/Test_Blas2_syr.hpp(1533): here
19:28:38             instantiation of "int test_syr<ScalarX,ScalarA,Device>(const std::__cxx11::string &) [with ScalarX=double, ScalarA=double, Device=Kokkos::Cuda]" 
19:28:38 /home/jenkins/weaver/workspace/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/Trilinos/kokkos-kernels/blas/unit_test/Test_Blas2_syr.hpp(1727): here
```

@eeprude are you able to investigate?

**Reproducer** (Weaver testbed, rhel8 queue):
```bash
# Repos
git clone -b develop https://github.com/trilinos/Trilinos.git
git clone -b develop https://github.com/kokkos/kokkos.git
git clone -b develop https://github.com/kokkos/kokkos-kernels.git
# Symbolic link to your kokkos and kokkos-kernels repos in Trilinos source directory for source override
cd Trilinos
ln -s <path-to-your-repo>/kokkos kokkos
ln -s <path-to-your-repo>/kokkos-kernels kokkos-kernels

cd $HOME
mkdir -p build
cd build

source /etc/profile.d/modules.sh
source /projects/ppc64le-pwr9-rhel8/legacy-env.sh
module load git  cmake/3.23.1 cuda/11.2.2/gcc/8.3.1 openmpi/4.1.1/gcc/8.3.1/cuda/11.2.2 openblas/0.3.18/gcc/8.3.1
export OMPI_CXX=$KOKKOS_PATH/bin/nvcc_wrapper

TESTS=ON

cmake \
 -D CMAKE_CXX_COMPILER=`which mpicxx` \
 -D CMAKE_CXX_FLAGS="-g" \
 -D CMAKE_C_COMPILER=`which mpicc` \
 -D CMAKE_C_FLAGS="-g" \
 -D CMAKE_Fortran_COMPILER=`which mpifort` \
 -D CMAKE_Fortran_FLAGS="-g" \
 -D CMAKE_BUILD_TYPE:STRING=RELEASE \
 -D CMAKE_CXX_STANDARD=17 \
 -D CMAKE_INSTALL_PREFIX=$PWD/install \
 -D BUILD_SHARED_LIBS=ON \
\
 -D TPL_ENABLE_CUDA:STRING=ON \
 -D TPL_ENABLE_MPI:STRING=ON \
 -D MPI_BASE_DIR:PATH="$OPENMPI_ROOT" \
 -D MPI_BIN_DIR:PATH="$OPENMPI_BIN" \
 -D MPI_EXEC_POST_NUMPROCS_FLAGS:STRING="-map-by;socket:PE=4" \
\
-D TPL_ENABLE_BLAS:STRING=ON \
  -D BLAS_LIBRARY_DIRS:FILEPATH="${OPENBLAS_ROOT}/lib" \
  -D BLAS_LIBRARY_NAMES:STRING="openblas" \
-D TPL_ENABLE_LAPACK:STRING=ON \
  -D LAPACK_INCLUDE_DIRS:FILEPATH="${OPENBLAS_ROOT}/include" \
  -D LAPACK_LIBRARY_DIRS:FILEPATH="${OPENBLAS_ROOT}/lib" \
  -D LAPACK_LIBRARY_NAMES:STRING="openblas" \
\
 -D Trilinos_ENABLE_COMPLEX=ON \
 -D Trilinos_ENABLE_TESTS=OFF \
 -D Trilinos_ENABLE_EXAMPLES=OFF \
 -D Trilinos_ENABLE_Kokkos=ON \
 -D Kokkos_ENABLE_CUDA=ON \
 -D Kokkos_ENABLE_CUDA_LAMBDA=ON \
 -D Kokkos_ENABLE_CUDA_UVM=ON \
 -D Kokkos_ARCH_VOLTA70=ON \
 -D Kokkos_ARCH_POWER9=ON \
 -D Kokkos_ENABLE_TESTS=OFF \
 -D Trilinos_ENABLE_KokkosKernels=ON \
 -D KokkosKernels_INST_MEMSPACE_CUDAUVMSPACE=ON \
 -D KokkosKernels_ENABLE_TESTS=ON \
 -D Trilinos_ENABLE_Tpetra=ON \
 -D Tpetra_ENABLE_CUDA=ON \
 -D Tpetra_ENABLE_SERIAL=ON \
 -D Tpetra_ENABLE_TESTS=${TESTS} \
 -D Trilinos_ENABLE_Sacado=ON \
 -D Sacado_ENABLE_TESTS=${TESTS} \
 -D Trilinos_ENABLE_Belos=ON \
 -D Belos_ENABLE_TESTS=${TESTS} \
\
 -D Trilinos_ENABLE_Phalanx=ON \
 -D Phalanx_ENABLE_TESTS=${TESTS} \
 -D Trilinos_ENABLE_Zoltan2=ON \
 -D Zoltan2_ENABLE_TESTS=${TESTS} \
 -D Trilinos_ENABLE_Adelus=ON \
 -D Adelus_ENABLE_TESTS=${TESTS} \
\
  -DKokkos_SOURCE_DIR_OVERRIDE:STRING=kokkos \
  -DKokkosKernels_SOURCE_DIR_OVERRIDE:STRING=kokkos-kernels \
$TRILINOS_DIR
```

**Comment by eeprude** [comment]
I will at it in the next hours, Nathan.

Ernesto.

From: Nathan Ellingwood ***@***.***>
Date: Wednesday, June 14, 2023 at 8:34 PM
To: kokkos/kokkos-kernels ***@***.***>
Cc: Prudencio, Ernesto Esteves ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] [kokkos/kokkos-kernels] Trilinos compilation errors, Cuda builds with UVM: error: static assertion failed with "Incompatible View copy construction" in blas/unit_test/Test_Blas2_syr.hpp(1727) (Issue #1869)

Trilinos builds with kokkos-kernels' develop branch began failing to compile with merge of #1837<https://github.com/kokkos/kokkos-kernels/pull/1837> in Cuda builds with UVM enabled

Compilation error snip:

19:28:38 /home/jenkins/weaver/workspace/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/Trilinos/kokkos/core/src/Kokkos_View.hpp(1319): error: static assertion failed with "Incompatible View copy construction"

19:28:38           detected during:

19:28:38             instantiation of "Kokkos::View<DataType, Properties...>::View(const Kokkos::View<RT, RP...> &, std::enable_if_t<Kokkos::Impl::ViewMapping<Kokkos::View<DataType, Properties...>::traits, Kokkos::View<RT, RP...>::traits, Kokkos::ViewTraits<DataType, Properties...>::specialize>::is_assignable_data_type, void> *) [with DataType=double **, Properties=<std::conditional_t<true, Kokkos::Cuda::array_layout, Kokkos::Cuda::array_layout>, Kokkos::Device<Kokkos::HostSpace::execution_space, Kokkos::Cuda::memory_space>, std::conditional_t<false, void, Kokkos::Experimental::DefaultViewHooks>>, RT=double **, RP=<Kokkos::LayoutLeft, Kokkos::HostSpace>]"

19:28:38 /home/jenkins/weaver/workspace/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/Trilinos/kokkos-kernels/blas/unit_test/Test_Blas2_syr.hpp(1498): here

19:28:38             instantiation of "void Test::SyrTester<ScalarX, tLayoutX, ScalarA, tLayoutA, Device>::callKkGerAndCompareKkSyrAgainstIt(const ScalarA &, TX &, Test::view_stride_adapter<Test::SyrTester<ScalarX, tLayoutX, ScalarA, tLayoutA, Device>::_ViewTypeA, false> &, const Test::SyrTester<ScalarX, tLayoutX, ScalarA, tLayoutA, Device>::_ViewTypeExpected &, const std::__cxx11::string &) [with ScalarX=double, tLayoutX=Kokkos::LayoutLeft, ScalarA=double, tLayoutA=Kokkos::LayoutLeft, Device=Kokkos::Cuda, TX=Kokkos::View<double *, Kokkos::LayoutLeft, Kokkos::Cuda>]"

19:28:38 /home/jenkins/weaver/workspace/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/Trilinos/kokkos-kernels/blas/unit_test/Test_Blas2_syr.hpp(324): here

19:28:38             instantiation of "void Test::SyrTester<ScalarX, tLayoutX, ScalarA, tLayoutA, Device>::test(int, int, __nv_bool, __nv_bool, __nv_bool) [with ScalarX=double, tLayoutX=Kokkos::LayoutLeft, ScalarA=double, tLayoutA=Kokkos::LayoutLeft, Device=Kokkos::Cuda]"

19:28:38 /home/jenkins/weaver/workspace/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/Trilinos/kokkos-kernels/blas/unit_test/Test_Blas2_syr.hpp(1533): here

19:28:38             instantiation of "int test_syr<ScalarX,ScalarA,Device>(const std::__cxx11::string &) [with ScalarX=double, ScalarA=double, Device=Kokkos::Cuda]"

19:28:38 /home/jenkins/weaver/workspace/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/Trilinos/kokkos-kernels/blas/unit_test/Test_Blas2_syr.hpp(1727): here

@eeprude<https://github.com/eeprude> are you able to investigate?

Reproducer (Weaver testbed, rhel8 queue):

# Repos

git clone -b develop https://github.com/trilinos/Trilinos.git

git clone -b develop https://github.com/kokkos/kokkos.git

git clone -b develop https://github.com/kokkos/kokkos-kernels.git

# Symbolic link to your kokkos and kokkos-kernels repos in Trilinos source directory for source override

cd Trilinos

ln -s <path-to-your-repo>/kokkos kokkos

ln -s <path-to-your-repo>/kokkos-kernels kokkos-kernels



cd $HOME

mkdir -p build

cd build



source /etc/profile.d/modules.sh

source /projects/ppc64le-pwr9-rhel8/legacy-env.sh

module load git  cmake/3.23.1 cuda/11.2.2/gcc/8.3.1 openmpi/4.1.1/gcc/8.3.1/cuda/11.2.2 openblas/0.3.18/gcc/8.3.1

export OMPI_CXX=$KOKKOS_PATH/bin/nvcc_wrapper



TESTS=ON



cmake \

 -D CMAKE_CXX_COMPILER=`which mpicxx` \

 -D CMAKE_CXX_FLAGS="-g" \

 -D CMAKE_C_COMPILER=`which mpicc` \

 -D CMAKE_C_FLAGS="-g" \

 -D CMAKE_Fortran_COMPILER=`which mpifort` \

 -D CMAKE_Fortran_FLAGS="-g" \

 -D CMAKE_BUILD_TYPE:STRING=RELEASE \

 -D CMAKE_CXX_STANDARD=17 \

 -D CMAKE_INSTALL_PREFIX=$PWD/install \

 -D BUILD_SHARED_LIBS=ON \

\

 -D TPL_ENABLE_CUDA:STRING=ON \

 -D TPL_ENABLE_MPI:STRING=ON \

 -D MPI_BASE_DIR:PATH="$OPENMPI_ROOT" \

 -D MPI_BIN_DIR:PATH="$OPENMPI_BIN" \

 -D MPI_EXEC_POST_NUMPROCS_FLAGS:STRING="-map-by;socket:PE=4" \

\

-D TPL_ENABLE_BLAS:STRING=ON \

  -D BLAS_LIBRARY_DIRS:FILEPATH="${OPENBLAS_ROOT}/lib" \

  -D BLAS_LIBRARY_NAMES:STRING="openblas" \

-D TPL_ENABLE_LAPACK:STRING=ON \

  -D LAPACK_INCLUDE_DIRS:FILEPATH="${OPENBLAS_ROOT}/include" \

  -D LAPACK_LIBRARY_DIRS:FILEPATH="${OPENBLAS_ROOT}/lib" \

  -D LAPACK_LIBRARY_NAMES:STRING="openblas" \

\

 -D Trilinos_ENABLE_COMPLEX=ON \

 -D Trilinos_ENABLE_TESTS=OFF \

 -D Trilinos_ENABLE_EXAMPLES=OFF \

 -D Trilinos_ENABLE_Kokkos=ON \

 -D Kokkos_ENABLE_CUDA=ON \

 -D Kokkos_ENABLE_CUDA_LAMBDA=ON \

 -D Kokkos_ENABLE_CUDA_UVM=ON \

 -D Kokkos_ARCH_VOLTA70=ON \

 -D Kokkos_ARCH_POWER9=ON \

 -D Kokkos_ENABLE_TESTS=OFF \

 -D Trilinos_ENABLE_KokkosKernels=ON \

 -D KokkosKernels_INST_MEMSPACE_CUDAUVMSPACE=ON \

 -D KokkosKernels_ENABLE_TESTS=ON \

 -D Trilinos_ENABLE_Tpetra=ON \

 -D Tpetra_ENABLE_CUDA=ON \

 -D Tpetra_ENABLE_SERIAL=ON \

 -D Tpetra_ENABLE_TESTS=${TESTS} \

 -D Trilinos_ENABLE_Sacado=ON \

 -D Sacado_ENABLE_TESTS=${TESTS} \

 -D Trilinos_ENABLE_Belos=ON \

 -D Belos_ENABLE_TESTS=${TESTS} \

\

 -D Trilinos_ENABLE_Phalanx=ON \

 -D Phalanx_ENABLE_TESTS=${TESTS} \

 -D Trilinos_ENABLE_Zoltan2=ON \

 -D Zoltan2_ENABLE_TESTS=${TESTS} \

 -D Trilinos_ENABLE_Adelus=ON \

 -D Adelus_ENABLE_TESTS=${TESTS} \

\

  -DKokkos_SOURCE_DIR_OVERRIDE:STRING=kokkos \

  -DKokkosKernels_SOURCE_DIR_OVERRIDE:STRING=kokkos-kernels \

$TRILINOS_DIR

**Comment by ndellingwood** [comment]
Thanks @eeprude ! This is not impacting the 4.1 release so no rush, let me know if you need help getting setup to build Trilinos with the develop branches

**Comment by ndellingwood** [comment]
With the merge of #1870 the nightly build just passed its next run, thanks for the fast fix @eeprude !
I'll mark this issue as InDevelop and close
