### ISSUE TITLE
Trilinos Cuda_Serial nightly build failure with BatchedDblBufGemm update

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#1121]
One of our nightly Trilinos Cuda_Serial (cuda/9.2, Kepler arch) builds https://jenkins-son.sandia.gov/job/KokkosKernels_Trilinos_TpetraCore_Sacado_KokkosDev_CUDA92_opt/346 began failing with merge of #1095, sample output:

```
17:50:25 /home/jenkins/jenkins-new/workspace/KokkosKernels_Trilinos_TpetraCore_Sacado_KokkosDev_CUDA92_opt/Trilinos/kokkos/core/src/Cuda/Kokkos_Cuda_KernelLaunch.hpp(320): error: A type that is defined inside a class and has private or protected access ("KokkosBatched::Impl::BatchedDblBufGemm<KokkosBatched::Trans::NoTranspose, KokkosBatched::Trans::NoTranspose, KokkosBatched::BatchLayout::Right, KokkosBatched::BatchedGemmHandle, default_scalar, view_type_3d, view_type_3d, view_type_3d, KokkosBatched::BoundsCheck::No, 32, 32, 8>::__Functor<Kokkos::Impl::CudaTeamMember, 4, 4, 8, 8>") cannot be used in the template argument type of a __global__ function template instantiation, unless the class is local to a __device__ or __global__ function
...
```

@e10harvey are you able to take a look? This can be reproduced on kokkos-dev, with a source override of the kokkos and kokkos-kernels develop branches (via symbolic link to local repos in the Trilinos source directory) and the kokkos-promotion branch of Trilinos with this configure:

```
export ATDM_CONFIG_REGISTER_CUSTOM_CONFIG_DIR=${TRILINOS_DIR}/cmake/std/atdm/contributed/kokkos-dev
source ${TRILINOS_DIR}/cmake/std/atdm/load-env.sh kokkos-dev-cuda-opt

export OMPI_CXX=$KOKKOS_DIR/bin/nvcc_wrapper

cmake \
 -GNinja \
 -DTrilinos_CONFIGURE_OPTIONS_FILE:STRING=cmake/std/atdm/ATDMDevEnv.cmake \
 -DCMAKE_INSTALL_PREFIX="${PWD}/install" \
 -DCMAKE_CXX_STANDARD="14" \
 -DTrilinos_ENABLE_TESTS=OFF \
 -DTrilinos_ENABLE_ALL_PACKAGES=OFF \
 -DTrilinos_ENABLE_Kokkos=ON \
  -DKokkos_ARCH_KEPLER35=ON \
 -DTrilinos_ENABLE_KokkosKernels=ON \
  -DKokkosKernels_ENABLE_TESTS=ON \
 -DTrilinos_ENABLE_TpetraCore=ON \
   -DTpetra_ENABLE_TESTS=ON \
 -DKokkos_ENABLE_CUDA=ON \
  -DTrilinos_ENABLE_Sacado=ON \
   -DSacado_ENABLE_TESTS=ON \
 -DKokkos_SOURCE_DIR_OVERRIDE:STRING=kokkos \
 -DKokkosKernels_SOURCE_DIR_OVERRIDE:STRING=kokkos-kernels \
$TRILINOS_DIR 2>&1 | tee configure.out

```

**Comment by ndellingwood** [comment]
This is also occurring in Cuda builds on Weaver with xl as host compiler (separate from Trilinos)

```
module load git cmake/3.19.3 cuda/10.1.105 gcc/7.4.0 ibm/xl/16.1.1

CXXEXTRAFLAGS="-qxflag=disable__cplusplusOverride -Wno-unused-function -O3 -Wall -Wunused-parameter -Wshadow -pedantic -Wsign-compare -Wtype-limits -Wuninitialized"

$KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-cuda --with-serial --compiler=xlC --cxxflags="${CXXEXTRAFLAGS}"  --arch=Power9,Volta70 --kokkos-path=${KOKKOS_PATH} --kokkoskernels-path=${KOKKOSKERNELS_PATH} --with-cuda-options=enable_lambda
```

**Comment by e10harvey** [comment]
Thanks, @ndellingwood ! I updated the two jenkins projects with parameters for the kokkos-kernels source repo and branch to streamline testing fixes going forward.
