### PR TITLE
Fix #527

### LINKED ISSUE #527: Link errors building KokkosSparse_gs.exe perf test
With the kokkos-kernels develop branch I'm unable to build the gauss-seidel performance test `KokkosSparse_gs.cpp` due to link errors:

<details>
 <summary>LinkErrors</summary>

```
g++  KokkosSparse_gs.o -L/Users/ndellin/Research/kokkos_items/kokkos-kernels/testing/ETILinkError/install/lib -L./ -lkokkos_kernels -lkokkos -    ldl -lpthread -L/Users/ndellin/Research/kokkos_items/kokkos-kernels/testing/ETILinkError/kokkos/install/lib -fopenmp   -o KokkosSparse_gs.exe
Undefined symbols for architecture x86_64:
  "KokkosSparse::Impl::GAUSS_SEIDEL_APPLY<KokkosKernels::Experimental::KokkosKernelsHandle<unsigned long const, int const, double const, Kokkos:: OpenMP, Kokkos::HostSpace, Kokkos::HostSpace>, Kokkos::View<unsigned long const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::     HostSpace>, Kokkos::MemoryTraits<1u> >, Kokkos::View<int const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::  MemoryTraits<1u> >, Kokkos::View<double const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u>   >, Kokkos::View<double**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u> >, Kokkos::View<double  const**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u> >, false, false>::                       gauss_seidel_apply(KokkosKernels::Experimental::KokkosKernelsHandle<unsigned long const, int const, double const, Kokkos::OpenMP, Kokkos::        HostSpace, Kokkos::HostSpace>*, int, int, Kokkos::View<unsigned long const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::          HostSpace>, Kokkos::MemoryTraits<1u> >, Kokkos::View<int const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::  MemoryTraits<1u> >, Kokkos::View<double const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u>   >, Kokkos::View<double**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u> >, Kokkos::View<double  const**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u> >, bool, bool, double, int, bool,        bool)", referenced from:
      void KokkosSparse::Experimental::symmetric_gauss_seidel_apply<KokkosKernels::Experimental::KokkosKernelsHandle<unsigned long, int, double,  Kokkos::OpenMP, Kokkos::HostSpace, Kokkos::HostSpace>, Kokkos::View<unsigned long const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP,      Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >, Kokkos::View<int*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >, Kokkos::View<double*, Kokkos::LayoutRight, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, void>, Kokkos::View<double*,    Kokkos::LayoutRight, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >, Kokkos::View<double*, Kokkos::LayoutRight,    Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> > >(KokkosKernels::Experimental::KokkosKernelsHandle<unsigned long,   int, double, Kokkos::OpenMP, Kokkos::HostSpace, Kokkos::HostSpace>*, KokkosKernels::Experimental::KokkosKernelsHandle<unsigned long, int, double, Kokkos::OpenMP, Kokkos::HostSpace, Kokkos::HostSpace>::const_nnz_lno_t, KokkosKernels::Experimental::KokkosKernelsHandle<unsigned long, int,      double, Kokkos::OpenMP, Kokkos::HostSpace, Kokkos::HostSpace>::const_nnz_lno_t, Kokkos::View<unsigned long const*, Kokkos::LayoutLeft, Kokkos::   Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >, Kokkos::View<int*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP,      Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >, Kokkos::View<double*, Kokkos::LayoutRight, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>,     void>, Kokkos::View<double*, Kokkos::LayoutRight, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >, Kokkos::         View<double*, Kokkos::LayoutRight, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >, bool, bool, KokkosKernels::     Experimental::KokkosKernelsHandle<unsigned long, int, double, Kokkos::OpenMP, Kokkos::HostSpace, Kokkos::HostSpace>::nnz_scalar_t, int) in        KokkosSparse_gs.o
  "KokkosSparse::Impl::GAUSS_SEIDEL_NUMERIC<KokkosKernels::Experimental::KokkosKernelsHandle<unsigned long const, int const, double const,        Kokkos::OpenMP, Kokkos::HostSpace, Kokkos::HostSpace>, Kokkos::View<unsigned long const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP,      Kokkos::HostSpace>, Kokkos::MemoryTraits<1u> >, Kokkos::View<int const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>,   Kokkos::MemoryTraits<1u> >, Kokkos::View<double const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::           MemoryTraits<1u> >, false, false>::gauss_seidel_numeric(KokkosKernels::Experimental::KokkosKernelsHandle<unsigned long const, int const, double   const, Kokkos::OpenMP, Kokkos::HostSpace, Kokkos::HostSpace>*, int, int, Kokkos::View<unsigned long const*, Kokkos::LayoutLeft, Kokkos::          Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u> >, Kokkos::View<int const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::       OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u> >, Kokkos::View<double const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::   HostSpace>, Kokkos::MemoryTraits<1u> >, bool)", referenced from:
      void KokkosSparse::Experimental::gauss_seidel_numeric<KokkosKernels::Experimental::KokkosKernelsHandle<unsigned long, int, double, Kokkos:: OpenMP, Kokkos::HostSpace, Kokkos::HostSpace>, Kokkos::View<unsigned long const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::     HostSpace>, Kokkos::MemoryTraits<0u> >, Kokkos::View<int*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::        MemoryTraits<0u> >, Kokkos::View<double*, Kokkos::LayoutRight, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, void> >(KokkosKernels::         Experimental::KokkosKernelsHandle<unsigned long, int, double, Kokkos::OpenMP, Kokkos::HostSpace, Kokkos::HostSpace>*, KokkosKernels::             Experimental::KokkosKernelsHandle<unsigned long, int, double, Kokkos::OpenMP, Kokkos::HostSpace, Kokkos::HostSpace>::const_nnz_lno_t,             KokkosKernels::Experimental::KokkosKernelsHandle<unsigned long, int, double, Kokkos::OpenMP, Kokkos::HostSpace, Kokkos::HostSpace>::              const_nnz_lno_t, Kokkos::View<unsigned long const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::               MemoryTraits<0u> >, Kokkos::View<int*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >, Kokkos::View<double*, Kokkos::LayoutRight, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, void>, bool) in KokkosSparse_gs.o
  "KokkosSparse::Impl::GAUSS_SEIDEL_SYMBOLIC<KokkosKernels::Experimental::KokkosKernelsHandle<unsigned long const, int const, double const,       Kokkos::OpenMP, Kokkos::HostSpace, Kokkos::HostSpace>, Kokkos::View<unsigned long const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP,      Kokkos::HostSpace>, Kokkos::MemoryTraits<1u> >, Kokkos::View<int const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>,   Kokkos::MemoryTraits<1u> >, false, false>::gauss_seidel_symbolic(KokkosKernels::Experimental::KokkosKernelsHandle<unsigned long const, int const, double const, Kokkos::OpenMP, Kokkos::HostSpace, Kokkos::HostSpace>*, int, int, Kokkos::View<unsigned long const*, Kokkos::LayoutLeft, Kokkos::   Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u> >, Kokkos::View<int const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::       OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u> >, bool)", referenced from:
      void runGS<unsigned long, int, Kokkos::OpenMP>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::       __cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool) in KokkosSparse_gs.o
  "KokkosSparse::Impl::SPMV<double const, int const, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u>, unsigned long   const, double const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<3u>, double*, Kokkos::          LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u>, false, false>::spmv(char const*, double const&,          KokkosSparse::CrsMatrix<double const, int const, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u>, unsigned long       const> const&, Kokkos::View<double const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<3u> >      const&, double const&, Kokkos::View<double*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u> >    const&)", referenced from:
      void runGS<unsigned long, int, Kokkos::OpenMP>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::       __cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool) in KokkosSparse_gs.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
```
</details>

develop branch SHA: 4cd9627e5bbe2bef8554c7bc6ea637bf849df2b8

OpenMP build with gcc/6.5 on my Mac laptop

Configuration:
```
KOKKOS_PATH=${HOME}/kokkos #path to kokkos source
KOKKOSKERNELS_SCALARS=double
KOKKOSKERNELS_LAYOUTS=LayoutLeft #the layout types to instantiate.
KOKKOSKERNELS_ORDINALS=int #ordinal types to instantiate
KOKKOSKERNELS_OFFSETS=int #offset types to instantiate
KOKKOSKERNELS_PATH=../.. #path to kokkos-kernels top directory.
KOKKOSKERNELS_OPTIONS=eti-only #options for kokkoskernels  
CXXFLAGS="-Wall -pedantic -Werror -O3 -g -Wshadow -Wsign-compare -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized"
CXX=g++ #${KOKKOS_PATH}/bin/nvcc_wrapper
KOKKOS_DEVICES=OpenMP #devices Cuda...

../../scripts/generate_makefile.bash --kokkoskernels-path=${KOKKOSKERNELS_PATH} --with-scalars=${KOKKOSKERNELS_SCALARS} --with-                   ordinals=${KOKKOSKERNELS_ORDINALS} --with-offsets=${KOKKOSKERNELS_OFFSETS} --kokkos-path=${KOKKOS_PATH} --with-devices=${KOKKOS_DEVICES} --       arch=${KOKKOS_ARCHS} --compiler=${CXX} --with-options=${KOKKOSKERNELS_OPTIONS}  --cxxflags="${CXXFLAGS}" --with-kokkos-                           options=${KOKKOS_OPTIONS} --with-layouts=${KOKKOSKERNELS_LAYOUTS}
```

### PR DESCRIPTION
**Pull request by brian-kelley**
In GS, spiluk, sptrsv, and spmv_struct perf tests, use offset/ordinal ETI macros to determine what types to use.

@vqd8a I made 2 minor changes to spiluk, which are
- print a message if CUDA is not enabled
- don't run cuSPARSE if ordinal/offset is not int/int. If the TPL is enabled, print a message saying why it's not being run.

@ndellingwood, I built this successfully using generate_makefile in 3 OpenMP configurations: int/int, int/size_t and int64/size_t. The original issue was just for int/int and GS, but I thought we might as well allow the other combinations. I'm running the usual spot-checks now but you might just want to merge it now.

### CODE REVIEW

**Comment by ndellingwood** [comment]
@brian-kelley I can run a spot-check on kokkos-dev-2 if the white queue is busy, let me know.

**Comment by brian-kelley** [comment]
@ndellingwood I have jobs running on white and bowman currently.

**Comment by brian-kelley** [comment]
@ndellingwood The test ``openmp.gemm_complex_double`` is failing on white. But so far, everything in perf_tests/ is building ok.

**Comment by ndellingwood** [comment]
> openmp.gemm_complex_double

@brian-kelley which host compiler? If that is with XL that is a known issue (#344); the `KokkosKernels_White_CudaOpenMP_cuda_10_gcc_740` and `KokkosKernels_White_CudaOpenMP_cuda_92_gcc_720` nightlies are passing.

**Comment by brian-kelley** [comment]
@ndellingwood For me it failed on the GCCs as well (6.4, 7.2, and 7.4).

**Comment by ndellingwood** [comment]
> For me it failed on the GCCs as well (6.4, 7.2, and 7.4).

@brian-kelley is this using the `test_all_sandia` or `cm_test_all_sandia` script?

**Comment by brian-kelley** [comment]
It also failed with intel 16 on bowman.

**Comment by brian-kelley** [comment]
@ndellingwood Oh, I was still using test_all_sandia in all the batch jobs. Let me try with cm.

**Comment by brian-kelley** [comment]
@ndellingwood The ``cm_test_all_sandia`` failed on bowman with this, right after installing kokkos:
```
... installing kokkos stuff ...
-- Installing: /ascldap/users/bmkelle/KKWork/CMakeBowmanTesting/TestAll_2019-12-16_14.12.44/intel/17.2.174/OpenMP_Serial-release/kokkos-install/include/KokkosCore_config.h
-- Installing: /ascldap/users/bmkelle/KKWork/CMakeBowmanTesting/TestAll_2019-12-16_14.12.44/intel/17.2.174/OpenMP_Serial-release/kokkos-install/lib/CMake/Kokkos/KokkosConfig.cmake
-- Installing: /ascldap/users/bmkelle/KKWork/CMakeBowmanTesting/TestAll_2019-12-16_14.12.44/intel/17.2.174/OpenMP_Serial-release/kokkos-install/lib/CMake/Kokkos/KokkosTargets.cmake
-- Installing: /ascldap/users/bmkelle/KKWork/CMakeBowmanTesting/TestAll_2019-12-16_14.12.44/intel/17.2.174/OpenMP_Serial-release/kokkos-install/lib/CMake/Kokkos/KokkosTargets-noconfig.cmake
-- Installing: /ascldap/users/bmkelle/KKWork/CMakeBowmanTesting/TestAll_2019-12-16_14.12.44/intel/17.2.174/OpenMP_Serial-release/kokkos-install/lib/pkgconfig/kokkos.pc

cmake -DCMAKE_CXX_COMPILER=/home/projects/x86-64-knl/intel/compilers/2017/compilers_and_libraries_2017.2.174/linux/bin/intel64/icpc -DKokkos_DIR=/ascldap/users/bmkelle/KKWork/CMakeBowmanTesting/TestAll_2019-12-16_14.12.44/intel/17.2.174/OpenMP_Serial-release/kokkos-install/lib/cmake/Kokkos -DCMAKE_CXX_FLAGS=-O3 -Wall -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized  -DCMAKE_INSTALL_PREFIX= -DKokkosKernels_ENABLE_TESTS=ON -DCMAKE_EXE_LINKER_FLAGS= /ascldap/users/bmkelle/KKWork/kokkos-kernels

-- The CXX compiler identification is Intel 17.0.2.20170213
-- Check for working CXX compiler: /home/projects/x86-64-knl/intel/compilers/2017/compilers_and_libraries_2017.2.174/linux/bin/intel64/icpc
-- Check for working CXX compiler: /home/projects/x86-64-knl/intel/compilers/2017/compilers_and_libraries_2017.2.174/linux/bin/intel64/icpc -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting policy CMP0074 to use <Package>_ROOT variables
-- Found Kokkos at /ascldap/users/bmkelle/KKWork/CMakeBowmanTesting/TestAll_2019-12-16_14.12.44/intel/16.4.258/Serial-release/kokkos-install
CMake Error at CMakeLists.txt:53 (KOKKOS_CHECK):
  Unknown CMake command "KOKKOS_CHECK".


-- Configuring incomplete, errors occurred!
See also "/ascldap/users/bmkelle/KKWork/CMakeBowmanTesting/TestAll_2019-12-16_14.12.44/intel/17.2.174/OpenMP_Serial-release/CMakeFiles/CMakeOutput.log".

```

**Comment by ndellingwood** [comment]
> The `cm_test_all_sandia` failed on bowman with this, right after installing kokkos

I think we just talked offline about this, but that was probably due to use of kokkos' master instead of develop branch, which is required for the CMake changes.

**Comment by brian-kelley** [comment]
@ndellingwood Yeah I'm running it again with kokkos develop on both machines, so I'll know in a few minutes if GCC + OpenMP still fails here.

**Comment by ndellingwood** [comment]
Also, we're still using `test_all_sandia` for nightlies but getting closer to making the change very soon. Jeremy has been running a lot of tests, so the scripts are getting the extensive testing they need.

**Comment by brian-kelley** [comment]
cm_test_all_sandia is showing build errors in Test_Common_Sorting.hpp, which was in another recent PR from me. I had been testing it with kokkos-kernels as a Trilinos subpackage before, so I probably never tested it with -Werror. I'll fix that ASAP.

**Comment by brian-kelley** [comment]
@ndellingwood 
- Since this is not related to the new errors, can we just merge this now? That way I can be working off of develop when I fix the sorting tests
- The KokksBlas unit tests successfully built and ran, but they don't have scalar=complex_double by default. I'm running it again with ``--with-scalars=double,complex_double``

**Comment by ndellingwood** [comment]
Merged, thanks @brian-kelley !

**Comment by brian-kelley** [comment]
@ndellingwood It turns out that @jjwilke saw the Test_Common_Sorting build errors and fixed them last Friday (thanks Jeremy!).

**Comment by ndellingwood** [comment]
Great, thanks! Will cross-reference #533, I reviewed but had forgotten that fix occurred.

**Comment by mhoemmen** [comment]
@brian-kelley wrote:
> Edit: with complex manually enabled, `serial.gemm_complex_double` and `openmp.gemm_complex_double` still fail with `cm_test_all_sandia`.

If you're worried about the BLAS library itself, one way to do an independent test is to run the `Teuchos::BLAS` tests.  They live in the TeuchosNumerics subpackage of Trilinos.
