### ISSUE TITLE
Nightly test failure: cuda/12.0 build, Test_Sparse_spmv.hpp(1016): error: no operator "=" matches these operands

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#2679]
Nightly kokkos-kernels builds with cuda/12.0 have the following compilation failures occuring:

**Error snip**:
```
15:15:40 /home/jenkins/weaver/workspace/KokkosKernels_Weaver_Cuda_Serial_cuda_1200_gcc_1130-cpp20/kokkos-kernels/sparse/unit_test/Test_Sparse_spmv.hpp(1016): error: no operator "=" matches these operands
15:15:40             operand types are: std::vector<Kokkos::Cuda, std::allocator<Kokkos::Cuda>> = std::array<Kokkos::CudaSpace::execution_space, 2UL>
15:15:40           detected during instantiation of "void test_spmv_all_interfaces_light<scalar_t,lno_t,size_type,layout_t,DeviceType>() [with scalar_t=double, lno_t=int, size_type=int, layout_t=Kokkos::LayoutLeft, DeviceType=CudaSpaceDevice]" 
15:15:40 /home/jenkins/weaver/workspace/KokkosKernels_Weaver_Cuda_Serial_cuda_1200_gcc_1130-cpp20/kokkos-kernels/test_common/Test_Common_Test_All_Type_Combos.hpp(61): here
15:15:40 
15:15:40 /home/jenkins/weaver/workspace/KokkosKernels_Weaver_Cuda_Serial_cuda_1200_gcc_1130-cpp20/kokkos-kernels/sparse/unit_test/Test_Sparse_spmv.hpp(1016): error: no operator "=" matches these operands
15:15:40             operand types are: std::vector<Kokkos::Cuda, std::allocator<Kokkos::Cuda>> = std::array<Kokkos::CudaSpace::execution_space, 2UL>
15:15:40           detected during instantiation of "void test_spmv_all_interfaces_light<scalar_t,lno_t,size_type,layout_t,DeviceType>() [with scalar_t=double, lno_t=int, size_type=size_t, layout_t=Kokkos::LayoutLeft, DeviceType=CudaSpaceDevice]" 
15:15:40 /home/jenkins/weaver/workspace/KokkosKernels_Weaver_Cuda_Serial_cuda_1200_gcc_1130-cpp20/kokkos-kernels/test_common/Test_Common_Test_All_Type_Combos.hpp(71): here
...
```

This follows merge of the following changes:

**Changes**

Git (git https://github.com/kokkos/kokkos.git)

    Fix configuration of nightly jenkins ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Weaver_Cuda_Serial_cuda_1200_gcc_1130-cpp20/545/changes#detail))
    Enable structured binding return for Experimental::partition_space() (#8114) ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Weaver_Cuda_Serial_cuda_1200_gcc_1130-cpp20/545/changes#detail))

Git (git https://github.com/kokkos/kokkos-kernels.git)

    Remove stray ; (#2671) ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_Weaver_Cuda_Serial_cuda_1200_gcc_1130-cpp20/545/changes#detail))

**Reproducer notes** (weaver testbed):
```bash
source /etc/profile.d/modules.sh
module purge
module load cmake git gcc/11.3.0 cuda/12.0.0

${KOKKOSKERNELS_PATH}/cm_generate_makefile.bash --with-cuda --with-serial --compiler=${KOKKOS_PATH}/bin/nvcc_wrapper --arch=Volta70,Power9 --with-cuda-options=enable_lambda --kokkos-path=${KOKKOS_PATH} --kokkoskernels-path=${KOKKOSKERNELS_PATH} --with-scalars='double,complex_double' --with-ordinals=int --with-offsets=int,size_t --cxxstandard=20 --kokkos-cmake-flags=-DKokkos_ENABLE_COMPLEX_ALIGN=OFF

make -j16
```

**Comment by ndellingwood** [comment]
Sample output from a Serial build of Trilinos:
```
20:35:55 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_Gcc_1130_OpenMPI_415_Serial/Trilinos/kokkos-kernels/sparse/unit_test/Test_Sparse_spmv.hpp:1016:22: error: no match for 'operator=' (operand types are 'std::vector<Kokkos::Serial>' and 'std::array<Kokkos::Serial, 2>')
20:35:55  1016 |     space_partitions = Kokkos::Experimental::partition_space(space, 1, 1);
20:35:55       |     ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
```

Seems to be related to kokkos/kokkos#8114 , @tcclevenger can you help us investigate?

**Comment by ndellingwood** [comment]
This seems to be occurring in several of the nightly builds, hitting each backend
Hip w/ rocm/6.0:
```
21:15:01 In file included from /home/jenkins/caraway-new/workspace/KokkosKernels_CarawayMI210_Rocm600_HipSerial/kokkos-kernels/sparse/unit_test/Test_Sparse.hpp:34:
21:15:01 /home/jenkins/caraway-new/workspace/KokkosKernels_CarawayMI210_Rocm600_HipSerial/kokkos-kernels/sparse/unit_test/Test_Sparse_spmv.hpp:1016:22: error: no viable overloaded '='
21:15:01     space_partitions = Kokkos::Experimental::partition_space(space, 1, 1);
```

**Comment by tcclevenger** [comment]
Yes, this is related to my PR, fix looks like it will be straightforward (return type changed for that version of `partition_space`. I'll take a look now.

**Comment by ndellingwood** [comment]
Looks like there may be a couple more places in Trilinos with a related issue, I'll open a new issue with better info but adding some details for now

Hip build - Ifpack2:
```
19:55:21 /home/jenkins/caraway-new/workspace/KokkosEco_Trilinos_Caraway_Rocm561_Hip_Serial_MI210/Trilinos/packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp:418:24: error: no viable overloaded '='
19:55:21         exec_instances =
19:55:21         ~~~~~~~~~~~~~~ ^
19:55:21 /home/jenkins/caraway-new/workspace/KokkosEco_Trilinos_Caraway_Rocm561_Hip_Serial_MI210/Trilinos/packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp:442:9: note: in instantiation of member function 'Ifpack2::BlockTriDiContainerDetails::AsyncableImport<Tpetra::RowMatrix<double, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>>::createExecutionSpaceInstances' requested here
19:55:21         createExecutionSpaceInstances();
19:55:21         ^
19:55:21 /home/jenkins/caraway-new/workspace/KokkosEco_Trilinos_Caraway_Rocm561_Hip_Serial_MI210/Trilinos/packages/ifpack2/src/Ifpack2_BlockTriDiContainer_impl.hpp:973:35: note: in instantiation of member function 'Ifpack2::BlockTriDiContainerDetails::AsyncableImport<Tpetra::RowMatrix<double, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>>::AsyncableImport' requested here
19:55:21           return Teuchos::rcp(new AsyncableImport<MatrixType>(domain_map, parsimonious_col_map, blocksize, dm2cm));
19:55:21                                   ^
19:55:21 /home/jenkins/caraway-new/workspace/KokkosEco_Trilinos_Caraway_Rocm561_Hip_Serial_MI210/Trilinos/packages/ifpack2/src/Ifpack2_BlockTriDiContainer_def.hpp:105:59: note: in instantiation of function template specialization 'Ifpack2::BlockTriDiContainerDetails::createBlockCrsAsyncImporter<Tpetra::RowMatrix<double, int, long long, Tpetra::KokkosCompat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace>>>' requested here
19:55:21       impl_->async_importer = BlockTriDiContainerDetails::createBlockCrsAsyncImporter<MatrixType>(impl_->A);
19:55:21                                                           ^
19:55:21 /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/stl_vector.h:582:7: note: candidate function not viable: no known conversion from 'std::array<Serial, sizeof...(Args)>' to 'const vector<Serial>' for 1st argument
19:55:21       operator=(const vector& __x);
19:55:21       ^
19:55:21 /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/stl_vector.h:596:7: note: candidate function not viable: no known conversion from 'std::array<Serial, sizeof...(Args)>' to 'vector<Serial>' for 1st argument
19:55:21       operator=(vector&& __x) noexcept(_Alloc_traits::_S_nothrow_move())
19:55:21       ^
19:55:21 /usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/stl_vector.h:617:7: note: candidate function not viable: no known conversion from 'std::array<Serial, sizeof...(Args)>' to 'initializer_list<value_type>' (aka 'initializer_list<Kokkos::Serial>') for 1st argument
19:55:21       operator=(initializer_list<value_type> __l)
```

Cuda build - Phalanx:
```
19:08:12 /home/jenkins/weaver/workspace/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/Trilinos/packages/phalanx/test/Kokkos/tKokkosFencing.cpp(91): error: no operator "=" matches these operands
19:08:12             operand types are: std::vector<Kokkos::Cuda, std::allocator<Kokkos::Cuda>> = std::array<Kokkos::DefaultExecutionSpace, 3UL>
19:08:12 
19:08:13 1 error detected in the compilation of "/home/jenkins/weaver/workspace/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/Trilinos/packages/phalanx/test/Kokkos/tKokkosFencing.cpp".
19:08:13 make[2]: *** [packages/phalanx/test/Kokkos/CMakeFiles/Phalanx_tKokkosFencing.dir/build.make:76: packages/phalanx/test/Kokkos/CMakeFiles/Phalanx_tKokkosFencing.dir/tKokkosFencing.cpp.o] Error 1
19:08:13 make[1]: *** [CMakeFiles/Makefile2:40727: packages/phalanx/test/Kokkos/CMakeFiles/Phalanx_tKokkosFencing.dir/all] Error 2
```
