### ISSUE TITLE
Nightly Trilinos cuda/11.2 build failures in Test_Blas1_abs

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#1798]
Nightly Trilinos builds with cuda/11.2 fail to compile in the Test_Blas1_abs test with the following output:

```
23:14:01 /home/jenkins/weaver-new/workspace/KokkosEco_Trilinos_Weaver_CUDA112_opt-develop/Trilinos/kokkos/core/src/Kokkos_View.hpp(1334): error: static assertion failed with "Incompatible View copy assignment"
23:14:01           detected during:
23:14:01             instantiation of "std::enable_if_t<Kokkos::Impl::ViewMapping<Kokkos::View<DataType, Properties...>::traits, Kokkos::View<RT, RP...>::traits, Kokkos::ViewTraits<DataType, Properties...>::specialize>::is_assignable_data_type, Kokkos::View<DataType, Properties...>> &Kokkos::View<DataType, Properties...>::operator=(const Kokkos::View<RT, RP...> &) [with DataType=double *, Properties=<std::conditional_t<true, Kokkos::Cuda::array_layout, Kokkos::Cuda::array_layout>, Kokkos::Device<Kokkos::HostSpace::execution_space, Kokkos::Cuda::memory_space>, std::conditional_t<false, void, Kokkos::Experimental::DefaultViewHooks>>, RT=double *, RP=<std::conditional_t<true, Kokkos::Cuda::array_layout, Kokkos::Cuda::array_layout>, Kokkos::HostSpace>]" 
23:14:01 /home/jenkins/weaver-new/workspace/KokkosEco_Trilinos_Weaver_CUDA112_opt-develop/Trilinos/kokkos-kernels/test_common/KokkosKernels_TestUtils.hpp(114): here
23:14:01             instantiation of "Test::view_stride_adapter<ViewType>::view_stride_adapter(const std::__cxx11::string &, int, int) [with ViewType=Kokkos::View<double *, Kokkos::LayoutLeft, Kokkos::Cuda>]" 
23:14:01 /home/jenkins/weaver-new/workspace/KokkosEco_Trilinos_Weaver_CUDA112_opt-develop/Trilinos/kokkos-kernels/blas/unit_test/Test_Blas1_abs.hpp(31): here
23:14:01             instantiation of "void Test::impl_test_abs<ViewTypeA,ViewTypeB,Device>(int) [with ViewTypeA=Kokkos::View<double *, Kokkos::LayoutLeft, Kokkos::Cuda>, ViewTypeB=Kokkos::View<double *, Kokkos::LayoutLeft, Kokkos::Cuda>, Device=Kokkos::Cuda]" 
23:14:01 /home/jenkins/weaver-new/workspace/KokkosEco_Trilinos_Weaver_CUDA112_opt-develop/Trilinos/kokkos-kernels/blas/unit_test/Test_Blas1_abs.hpp(132): here
23:14:01             instantiation of "int test_abs<ScalarA,ScalarB,Device>() [with ScalarA=double, ScalarB=double, Device=Kokkos::Cuda]" 
23:14:01 /home/jenkins/weaver-new/workspace/KokkosEco_Trilinos_Weaver_CUDA112_opt-develop/Trilinos/kokkos-kernels/blas/unit_test/Test_Blas1_abs.hpp(231): here
```

This is not occurring with the stand-alone kokkos-kernels builds

Presumably this is following the updates in #1794 , @brian-kelley can you investigate?

**Reproducer** (weaver rhel8 queue):
```bash
source /etc/profile.d/modules.sh

module load git  cmake/3.23.1 cuda/11.2.2/gcc/8.3.1 openmpi/4.1.1/gcc/8.3.1/cuda/11.2.2 openblas/0.3.18/gcc/8.3.1
module load metis/5.1.0/gcc/8.3.1 hdf5/1.10.7/gcc/8.3.1/openmpi/4.1.1 parmetis/4.0.3/gcc/8.3.1/openmpi/4.1.1 zlib/1.2.11/gcc/8.3.1 boost/1.70.0/gcc/8.3.1

export OMPI_CXX=$KOKKOS_DIR/bin/nvcc_wrapper

cmake \
 -D CMAKE_CXX_COMPILER="`which mpicxx`" \
 -D CMAKE_CXX_FLAGS="-g" \
 -D CMAKE_C_COMPILER="`which mpicc`" \
 -D CMAKE_C_FLAGS="-g" \
 -D CMAKE_Fortran_COMPILER="`which mpifort`" \
 -D CMAKE_Fortran_FLAGS="-g" \
 -D CMAKE_BUILD_TYPE:STRING=RELEASE \
 -D CMAKE_CXX_STANDARD=17 \
 -D CMAKE_INSTALL_PREFIX=$PWD/install \

 -D TPL_ENABLE_CUDA:STRING=ON \
 -D TPL_ENABLE_MPI:STRING=ON \
 -D MPI_BASE_DIR:PATH="$OPENMPI_ROOT" \
 -D MPI_BIN_DIR:PATH="$OPENMPI_BIN" \
 -D MPI_EXEC_POST_NUMPROCS_FLAGS:STRING="-map-by;socket:PE=4" \

-D TPL_ENABLE_BLAS:STRING=ON \
  -D BLAS_LIBRARY_DIRS:FILEPATH="$OPENBLAS_ROOT/lib" \
  -D BLAS_LIBRARY_NAMES:STRING="openblas" \
-D TPL_ENABLE_LAPACK:STRING=ON \
  -D LAPACK_INCLUDE_DIRS:FILEPATH="$OPENBLAS_ROOT/include" \
  -D LAPACK_LIBRARY_DIRS:FILEPATH="$OPENBLAS_ROOT/lib" \
  -D LAPACK_LIBRARY_NAMES:STRING="openblas" \

-D TPL_ENABLE_Boost:BOOL=ON \
  -D Boost_INCLUDE_DIRS:FILEPATH="$BOOST_ROOT/include" \
  -D Boost_LIBRARY_DIRS:FILEPATH="$BOOST_ROOT/lib" \
-D TPL_ENABLE_BoostLib:BOOL=ON \
  -D BoostLib_INCLUDE_DIRS:FILEPATH="$BOOST_ROOT/include" \
  -D BoostLib_LIBRARY_DIRS:FILEPATH="$BOOST_ROOT/lib" \
-D TPL_ENABLE_Netcdf:BOOL=OFF \

 -D Trilinos_ENABLE_TESTS=OFF \
 -D Trilinos_ENABLE_EXAMPLES=OFF \

 -D Trilinos_ENABLE_Kokkos=ON \
 -D Kokkos_ENABLE_CUDA=ON \
 -D Kokkos_ENABLE_CUDA_LAMBDA=ON \
 -D Kokkos_ENABLE_CUDA_UVM=ON \
 -D Kokkos_ARCH_VOLTA70=ON \
 -D Kokkos_ARCH_POWER9=ON \
 -D Kokkos_ENABLE_TESTS=ON \
 -D Trilinos_ENABLE_KokkosKernels=ON \
 -D KokkosKernels_ENABLE_TESTS=ON \
$TRILINOS_DIR
```

**Comment by brian-kelley** [comment]
Oops, this was just because for a View v, ``create_mirror_view(HostSpace(), v)`` is not always the same type as ``View::HostMirror``. The fix is ready in #1800 .
