### ISSUE TITLE
Nightly build compilation errors with cuda/11.1+gcc/8.3.0 in Test_Sparse_MergeMatrix.hpp

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#1905]
Nightly builds with sems-cuda/11.1+sems-gcc/8.3.0 fail to compile with error output:

```
/data/jenkins-new/workspace/KokkosKernels_semsrhel7gpu01_cuda111_gcc830_cpp17/kokkos-kernels/sparse/unit_test/Test_Sparse_MergeMatrix.hpp: In instantiation of 'void Test_Sparse_MergeMatrix::view_view_full_full() [with AEntry = int; BEntry = int; ExecSpace = Kokkos::Serial]':
/data/jenkins-new/workspace/KokkosKernels_semsrhel7gpu01_cuda111_gcc830_cpp17/kokkos-kernels/sparse/unit_test/Test_Sparse_MergeMatrix.hpp:362:49:   required from 'void Test_Sparse_MergeMatrix::test_view_view() [with AEntry = int; BEntry = int; ExecSpace = Kokkos::Serial]'
/data/jenkins-new/workspace/KokkosKernels_semsrhel7gpu01_cuda111_gcc830_cpp17/kokkos-kernels/sparse/unit_test/Test_Sparse_MergeMatrix.hpp:551:44:   required from 'void Test_Sparse_MergeMatrix::test_merge_matrix() [with AEntry = int; BEntry = int; ExecSpace = Kokkos::Serial]'
/data/jenkins-new/workspace/KokkosKernels_semsrhel7gpu01_cuda111_gcc830_cpp17/kokkos-kernels/sparse/unit_test/Test_Sparse_MergeMatrix.hpp:559:72:   required from here
/data/jenkins-new/workspace/KokkosKernels_semsrhel7gpu01_cuda111_gcc830_cpp17/kokkos-kernels/sparse/unit_test/Test_Sparse_MergeMatrix.hpp:294:31: error: 'vector' was not declared in this scope
       expect_mmd_entries(mmd, std::vector(mmd.size(), mmd_value_type(0)));
                         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/jenkins-new/workspace/KokkosKernels_semsrhel7gpu01_cuda111_gcc830_cpp17/kokkos-kernels/sparse/unit_test/Test_Sparse_MergeMatrix.hpp:294:31: note: suggested alternative:
/net/watson.sandia.gov/storage/fast/projects/sems/install/rhel7-x86_64/sems-compilers/tpl/gcc/8.3.0/gcc/4.8.5/base/odjqidm/include/c++/8.3.0/bits/stl_vector.h:339:7: note:   'std::vector'
     class vector : protected _Vector_base<_Tp, _Alloc>
       ^~~~~~
/data/jenkins-new/workspace/KokkosKernels_semsrhel7gpu01_cuda111_gcc830_cpp17/kokkos-kernels/sparse/unit_test/Test_Sparse_MergeMatrix.hpp:302:31: error: 'vector' was not declared in this scope
       expect_mmd_entries(mmd, std::vector(mmd.size(), mmd_value_type(1)));
                         ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/data/jenkins-new/workspace/KokkosKernels_semsrhel7gpu01_cuda111_gcc830_cpp17/kokkos-kernels/sparse/unit_test/Test_Sparse_MergeMatrix.hpp:302:31: note: suggested alternative:
/net/watson.sandia.gov/storage/fast/projects/sems/install/rhel7-x86_64/sems-compilers/tpl/gcc/8.3.0/gcc/4.8.5/base/odjqidm/include/c++/8.3.0/bits/stl_vector.h:339:7: note:   'std::vector'
     class vector : protected _Vector_base<_Tp, _Alloc>
```

This began following merge of one of these commits:

LowerBound: fully-qualified types ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_semsrhel7gpu01_cuda111_gcc830_cpp17/359/changes#detail))
    Iota: std::remove_const -> std::remove_const_t ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_semsrhel7gpu01_cuda111_gcc830_cpp17/359/changes#detail))
    ComparableCast: safe signed/unsigned integer comparisons ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_semsrhel7gpu01_cuda111_gcc830_cpp17/359/changes#detail))
    add MergeMatrixDiagonal abstraction ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_semsrhel7gpu01_cuda111_gcc830_cpp17/359/changes#detail))
    Blas: Don't document return values of functions that don't return ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_semsrhel7gpu01_cuda111_gcc830_cpp17/359/changes#detail))
    Add BsrMatrix SpMV perf test ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_semsrhel7gpu01_cuda111_gcc830_cpp17/359/changes#detail))
    ODE: adding adaptivity test for RK methods ([detail](https://jenkins-son.sandia.gov/job/KokkosKernels_semsrhel7gpu01_cuda111_gcc830_cpp17/359/changes#detail))

This is not occurring with other versions of Cuda in nightly builds, so might be tickling a compiler issue? Adding CompilerIssue label for now

The file `Test_Sparse_MergeMatrix.hpp` flagged by the compiler indicates this might follow from changes in #1780 , @cwpearson can you take a look?

**Reproducer**: 
```bash
# Sems modules
sh /projects/sems/modulefiles/utils/sems-v2-modules-init.sh
module purge
module load sems-cmake sems-gcc/8.3.0 sems-cuda/11.1.0

$KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-devices=Cuda,Serial --arch=Volta70 --compiler=$KOKKOS_PATH/bin/nvcc_wrapper --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="17" --kokkos-path=$KOKKOS_PATH --kokkoskernels-path=$KOKKOSKERNELS_PATH --with-scalars='double,complex_double' --with-ordinals=int --with-offsets=int,size_t --with-layouts=LayoutLeft --with-cuda-options=enable_lambda   --no-examples
```

**Comment by cwpearson** [comment]
Reproducer on `kokkos-dev-2`

```
export KOKKOS_PATH=
export KOKKOSKERNELS_PATH=

source /projects/sems/modulefiles/utils/sems-archive-modules-init.sh ; module use /home/projects/x86-64/modulefiles/local
module purge
module load sems-archive-env sems-archive-cmake/3.17.1 sems-archive-gcc/9.2.0 cuda/11.0

$KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-devices=Cuda,Serial --arch=Volta70 --compiler=$KOKKOS_PATH/bin/nvcc_wrapper --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="17" --kokkos-path=$KOKKOS_PATH --kokkoskernels-path=$KOKKOSKERNELS_PATH --with-scalars='double,complex_double' --with-ordinals=int --with-offsets=int,size_t --with-layouts=LayoutLeft --with-cuda-options=enable_lambda   --no-examples
```

**Comment by ndellingwood** [comment]
The failing nightlies mentioned in the OP are now passing after merge of #1909, thanks @cwpearson !
