### ISSUE TITLE
Nightly Trilinos compilation errors with cuda/11.2: KokkosSparse_spmv_impl.hpp(117): error: static assertion failed with "XVector must be a rank 1 View."

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#1951]
Nightly Trilinos builds with cuda/11.2.2+gcc/8.3.0 began to fail to compile after updates to kokkos-kernels develop branch with the following output:

```
19:09:44 /home/jenkins/weaver/workspace/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/Trilinos/kokkos-kernels/sparse/impl/KokkosSparse_spmv_impl.hpp(117): error: static assertion failed with "XVector must be a rank 1 View."
19:09:44           detected during:
19:09:44             instantiation of "KokkosSparse::Impl::SPMV_Functor<execution_space, AMatrix, XVector, YVector, dobeta, conjugate>::SPMV_Functor(KokkosSparse::Impl::SPMV_Functor<execution_space, AMatrix, XVector, YVector, dobeta, conjugate>::value_type, AMatrix, XVector, KokkosSparse::Impl::SPMV_Functor<execution_space, AMatrix, XVector, YVector, dobeta, conjugate>::value_type, YVector, int) [with execution_space=Kokkos::CudaUVMSpace::execution_space, AMatrix=KokkosSparse::CrsMatrix<std::add_const_t<long long>, std::add_const_t<int>, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, Kokkos::MemoryTraits<1U>, std::add_const_t<const size_t>>, XVector=Kokkos::View<std::add_const_t<std::add_const_t<long long>> **, std::conditional_t<true, Kokkos::Cuda::array_layout, Kokkos::Cuda::array_layout>, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, Kokkos::MemoryTraits<3U>>, YVector=Kokkos::View<long long **, std::conditional_t<true, Kokkos::Cuda::array_layout, Kokkos::Cuda::array_layout>, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, Kokkos::MemoryUnmanaged>, dobeta=0, conjugate=false]" 
19:09:44 (435): here
19:09:44             instantiation of "void KokkosSparse::Impl::spmv_beta_no_transpose<execution_space,AMatrix,XVector,YVector,dobeta,conjugate,<unnamed>>(const execution_space &, const KokkosKernels::Experimental::Controls &, YVector::const_value_type &, const AMatrix &, const XVector &, YVector::const_value_type &, const YVector &) [with execution_space=Kokkos::CudaUVMSpace::execution_space, AMatrix=KokkosSparse::CrsMatrix<std::add_const_t<long long>, std::add_const_t<int>, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, Kokkos::MemoryTraits<1U>, std::add_const_t<const size_t>>, XVector=Kokkos::View<std::add_const_t<std::add_const_t<long long>> **, std::conditional_t<true, Kokkos::Cuda::array_layout, Kokkos::Cuda::array_layout>, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, Kokkos::MemoryTraits<3U>>, YVector=Kokkos::View<long long **, std::conditional_t<true, Kokkos::Cuda::array_layout, Kokkos::Cuda::array_layout>, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, Kokkos::MemoryUnmanaged>, dobeta=0, conjugate=false, <unnamed>=(void *)nullptr]" 
19:09:44 (633): here
19:09:44             instantiation of "void KokkosSparse::Impl::spmv_beta<execution_space,AMatrix,XVector,YVector,dobeta>(const execution_space &, const KokkosKernels::Experimental::Controls &, const char *, YVector::const_value_type &, const AMatrix &, const XVector &, YVector::const_value_type &, const YVector &) [with execution_space=Kokkos::CudaUVMSpace::execution_space, AMatrix=KokkosSparse::CrsMatrix<std::add_const_t<long long>, std::add_const_t<int>, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, Kokkos::MemoryTraits<1U>, std::add_const_t<const size_t>>, XVector=Kokkos::View<std::add_const_t<std::add_const_t<long long>> **, std::conditional_t<true, Kokkos::Cuda::array_layout, Kokkos::Cuda::array_layout>, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, Kokkos::MemoryTraits<3U>>, YVector=Kokkos::View<long long **, std::conditional_t<true, Kokkos::Cuda::array_layout, Kokkos::Cuda::array_layout>, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, Kokkos::MemoryUnmanaged>, dobeta=0]" 
19:09:44 /home/jenkins/weaver/workspace/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/Trilinos/kokkos-kernels/sparse/impl/KokkosSparse_spmv_spec.hpp(184): here
19:09:44             instantiation of "void KokkosSparse::Impl::SPMV<ExecutionSpace, AMatrix, XVector, YVector, false, false>::spmv(const ExecutionSpace &, const KokkosKernels::Experimental::Controls &, const char *, const KokkosSparse::Impl::SPMV<ExecutionSpace, AMatrix, XVector, YVector, false, false>::coefficient_type &, const AMatrix &, const XVector &, const KokkosSparse::Impl::SPMV<ExecutionSpace, AMatrix, XVector, YVector, false, false>::coefficient_type &, const YVector &) [with ExecutionSpace=Kokkos::CudaUVMSpace::execution_space, AMatrix=KokkosSparse::CrsMatrix<std::add_const_t<long long>, std::add_const_t<int>, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, Kokkos::MemoryTraits<1U>, std::add_const_t<const size_t>>, XVector=Kokkos::View<std::add_const_t<std::add_const_t<long long>> **, std::conditional_t<true, Kokkos::Cuda::array_layout, Kokkos::Cuda::array_layout>, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, Kokkos::MemoryTraits<3U>>, YVector=Kokkos::View<long long **, std::conditional_t<true, Kokkos::Cuda::array_layout, Kokkos::Cuda::array_layout>, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, Kokkos::MemoryUnmanaged>]" 
19:09:44 /home/jenkins/weaver/workspace/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/Trilinos/kokkos-kernels/sparse/impl/KokkosSparse_spmv_spec.hpp(245): here
19:09:44             instantiation of "void KokkosSparse::Impl::SPMV_MV<ExecutionSpace, AMatrix, XVector, YVector, true, false, false>::spmv_mv(const ExecutionSpace &, const KokkosKernels::Experimental::Controls &, const char *, const KokkosSparse::Impl::SPMV_MV<ExecutionSpace, AMatrix, XVector, YVector, true, false, false>::coefficient_type &, const AMatrix &, const XVector &, const KokkosSparse::Impl::SPMV_MV<ExecutionSpace, AMatrix, XVector, YVector, true, false, false>::coefficient_type &, const YVector &) [with ExecutionSpace=Kokkos::CudaUVMSpace::execution_space, AMatrix=KokkosSparse::CrsMatrix<std::add_const_t<long long>, std::add_const_t<int>, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, Kokkos::MemoryTraits<1U>, std::add_const_t<const size_t>>, XVector=Kokkos::View<std::add_const_t<std::add_const_t<long long>> **, std::conditional_t<true, Kokkos::Cuda::array_layout, Kokkos::Cuda::array_layout>, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, Kokkos::MemoryTraits<3U>>, YVector=Kokkos::View<long long **, std::conditional_t<true, Kokkos::Cuda::array_layout, Kokkos::Cuda::array_layout>, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, Kokkos::MemoryUnmanaged>]" 
19:09:44 /home/jenkins/weaver/workspace/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/Trilinos/kokkos-kernels/sparse/src/KokkosSparse_spmv.hpp(773): here
19:09:44             instantiation of "void KokkosSparse::spmv(const ExecutionSpace &, KokkosKernels::Experimental::Controls, const char *, const AlphaType &, const AMatrix &, const XVector &, const BetaType &, const YVector &, const KokkosSparse::<unnamed>::RANK_TWO &) [with ExecutionSpace=Kokkos::CudaUVMSpace::execution_space, AlphaType=long long, AMatrix=KokkosSparse::CrsMatrix<long long, int, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, Kokkos::MemoryTraits<1U>, size_t>, XVector=Kokkos::View<std::add_const_t<long long> **, std::conditional_t<true, Kokkos::Cuda::array_layout, Kokkos::Cuda::array_layout>, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, std::conditional_t<false, void, Kokkos::Experimental::DefaultViewHooks>, std::conditional_t<false, void, Kokkos::MemoryManaged>>, BetaType=Tpetra::longlong, YVector=Kokkos::View<long long **, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, void>, <unnamed>=(void *)nullptr]" 
19:09:44 /home/jenkins/weaver/workspace/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/Trilinos/kokkos-kernels/sparse/src/KokkosSparse_spmv.hpp(870): here
19:09:44             instantiation of "void KokkosSparse::spmv(const ExecutionSpace &, KokkosKernels::Experimental::Controls, const char *, const AlphaType &, const AMatrix &, const XVector &, const BetaType &, const YVector &, const KokkosSparse::<unnamed>::RANK_TWO &) [with ExecutionSpace=Kokkos::CudaUVMSpace::execution_space, AlphaType=long long, AMatrix=KokkosSparse::Experimental::BsrMatrix<long long, int, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, void, size_t>, XVector=Kokkos::View<std::add_const_t<long long> **, std::conditional_t<true, Kokkos::Cuda::array_layout, Kokkos::Cuda::array_layout>, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, std::conditional_t<false, void, Kokkos::Experimental::DefaultViewHooks>, std::conditional_t<false, void, Kokkos::MemoryManaged>>, BetaType=Tpetra::longlong, YVector=Kokkos::View<long long **, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, void>, <unnamed>=(void *)nullptr]" 
19:09:44 /home/jenkins/weaver/workspace/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/Trilinos/kokkos-kernels/sparse/src/KokkosSparse_spmv.hpp(1142): here
19:09:44             instantiation of "void KokkosSparse::spmv(const ExecutionSpace &, KokkosKernels::Experimental::Controls, const char *, const AlphaType &, const AMatrix &, const XVector &, const BetaType &, const YVector &) [with ExecutionSpace=Kokkos::CudaUVMSpace::execution_space, AlphaType=long long, AMatrix=KokkosSparse::Experimental::BsrMatrix<long long, int, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, void, size_t>, XVector=Kokkos::View<std::add_const_t<long long> **, std::conditional_t<true, Kokkos::Cuda::array_layout, Kokkos::Cuda::array_layout>, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, std::conditional_t<false, void, Kokkos::Experimental::DefaultViewHooks>, std::conditional_t<false, void, Kokkos::MemoryManaged>>, BetaType=Tpetra::longlong, YVector=Kokkos::View<long long **, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, void>]" 
19:09:44 /home/jenkins/weaver/workspace/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/Trilinos/kokkos-kernels/sparse/src/KokkosSparse_spmv.hpp(1190): here
19:09:44             instantiation of "void KokkosSparse::spmv(KokkosKernels::Experimental::Controls, const char *, const AlphaType &, const AMatrix &, const XVector &, const BetaType &, const YVector &) [with AlphaType=long long, AMatrix=KokkosSparse::Experimental::BsrMatrix<long long, int, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, void, size_t>, XVector=Kokkos::View<std::add_const_t<long long> **, std::conditional_t<true, Kokkos::Cuda::array_layout, Kokkos::Cuda::array_layout>, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, std::conditional_t<false, void, Kokkos::Experimental::DefaultViewHooks>, std::conditional_t<false, void, Kokkos::MemoryManaged>>, BetaType=Tpetra::longlong, YVector=Kokkos::View<long long **, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, void>]" 
19:09:44 /home/jenkins/weaver/workspace/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/Trilinos/kokkos-kernels/sparse/src/KokkosSparse_spmv.hpp(1262): here
19:09:44             instantiation of "void KokkosSparse::spmv(const char *, const AlphaType &, const AMatrix &, const XVector &, const BetaType &, const YVector &) [with AlphaType=long long, AMatrix=KokkosSparse::Experimental::BsrMatrix<long long, int, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, void, size_t>, XVector=Kokkos::View<std::add_const_t<long long> **, std::conditional_t<true, Kokkos::Cuda::array_layout, Kokkos::Cuda::array_layout>, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, std::conditional_t<false, void, Kokkos::Experimental::DefaultViewHooks>, std::conditional_t<false, void, Kokkos::MemoryManaged>>, BetaType=Tpetra::longlong, YVector=Kokkos::View<long long **, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>, void>]" 
19:09:44 /home/jenkins/weaver/workspace/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/Trilinos/packages/tpetra/core/src/Tpetra_BlockCrsMatrix_def.hpp(1113): here
19:09:44             instantiation of "void Tpetra::BlockCrsMatrix<Scalar, LO, GO, Node>::localApplyBlockNoTrans(const Tpetra::BlockMultiVector<Scalar, LO, GO, Node> &, Tpetra::BlockMultiVector<Scalar, LO, GO, Node> &, Scalar, Scalar) [with Scalar=Tpetra::longlong, LO=int, GO=Tpetra::longlong, Node=Tpetra::Tpetra_KokkosCompat_KokkosCudaWrapperNode]" 
19:09:44 /home/jenkins/weaver/workspace/KokkosEco_Trilinos_Weaver_CUDA112_Shared_Cplx/Trilinos/packages/tpetra/core/src/Tpetra_BlockCrsMatrix_def.hpp(1076): here
...
```

The change to kokkos-kernels from the previous build was #1932 , @brian-kelley would you be able to investigate?

**Reproducer** (Weaver rhel8 queue):
```bash
# Repos
git clone -b develop https://github.com/trilinos/Trilinos.git
git clone -b develop https://github.com/kokkos/kokkos.git
git clone -b develop https://github.com/kokkos/kokkos-kernels.git
# Symbolic link to your kokkos and kokkos-kernels repos in Trilinos source directory for source override
cd Trilinos
ln -s <path-to-your-repo>/kokkos kokkos
ln -s <path-to-your-repo>/kokkos-kernels kokkos-kernels

cd $HOME
mkdir -p build
cd build

# Get an interactive node
bsub -Is -n 1 -q rhel8 -gpu "num=1" bash

# Environment
source /projects/ppc64le-pwr9-rhel8/legacy-env.sh
module purge
module load git cmake/3.23.1 cuda/11.2.2/gcc/8.3.1 openmpi/4.1.1/gcc/8.3.1/cuda/11.2.2 openblas/0.3.18/gcc/8.3.1
module list
export OMPI_CXX=$KOKKOS_PATH/bin/nvcc_wrapper

# Configuration
cmake \
 -D CMAKE_CXX_COMPILER="which mpicxx`" \
 -D CMAKE_CXX_FLAGS="-g" \
 -D CMAKE_C_COMPILER="which mpicc`" \
 -D CMAKE_C_FLAGS="-g" \
 -D CMAKE_Fortran_COMPILER="`which mpifort`" \
 -D CMAKE_Fortran_FLAGS="-g" \
 -D CMAKE_BUILD_TYPE:STRING=RELEASE \
 -D CMAKE_CXX_STANDARD=17 \
 -D BUILD_SHARED_LIBS=ON \
 -D CMAKE_INSTALL_PREFIX=$PWD/install \
 -D TPL_ENABLE_CUDA:STRING=ON \
 -D TPL_ENABLE_MPI:STRING=ON \
-D TPL_ENABLE_BLAS:STRING=ON \
  -D BLAS_LIBRARY_DIRS:FILEPATH="$OPENBLAS_ROOT/lib" \
  -D BLAS_LIBRARY_NAMES:STRING=openblas \
-D TPL_ENABLE_LAPACK:STRING=ON \
  -D LAPACK_INCLUDE_DIRS:FILEPATH="$OPENBLAS_ROOT/include" \
  -D LAPACK_LIBRARY_DIRS:FILEPATH="$OPENBLAS_ROOT/lib" \
  -D LAPACK_LIBRARY_NAMES:STRING=openblas \
 -D Trilinos_ENABLE_COMPLEX=ON \
 -D Trilinos_ENABLE_TESTS=OFF \
 -D Trilinos_ENABLE_EXAMPLES=OFF \
 -D Trilinos_ENABLE_Kokkos=ON \
 -D Kokkos_ENABLE_CUDA=ON \
 -D Kokkos_ENABLE_CUDA_LAMBDA=ON \
 -D Kokkos_ENABLE_CUDA_UVM=ON \
 -D Kokkos_ARCH_VOLTA70=ON \
 -D Kokkos_ARCH_POWER9=ON \
 -D Kokkos_ENABLE_TESTS=ON \
 -D Trilinos_ENABLE_KokkosKernels=ON \
 -D KokkosKernels_ENABLE_TESTS=ON \
 -D Trilinos_ENABLE_Tpetra=ON \
 -D Tpetra_ENABLE_CUDA=ON \
 -D Tpetra_ENABLE_SERIAL=ON \
 -D Tpetra_ENABLE_TESTS=ON \
 -D Trilinos_ENABLE_Sacado=ON \
 -D Sacado_ENABLE_TESTS=ON \
 -D Trilinos_ENABLE_Phalanx=ON \
 -D Phalanx_ENABLE_TESTS=ON \
 -D Trilinos_ENABLE_Adelus=ON \
 -D Adelus_ENABLE_TESTS=ON \
 -D KokkosKernels_INST_MEMSPACE_CUDAUVMSPACE=ON \
 -D Trilinos_ENABLE_Ifpack2=OFF \
 -D Ifpack2_ENABLE_TESTS=OFF \
 -D Trilinos_ENABLE_Amesos2=OFF \
 -D Trilinos_ENABLE_Stokhos=OFF \
 -D Trilinos_ENABLE_MueLu=OFF \
 -D Intrepid2_ENABLE_TESTS=OFF \
 -D Trilinos_ENABLE_ShyLU_NodeTacho=OFF \
  -DKokkos_SOURCE_DIR_OVERRIDE:STRING=kokkos \
  -DKokkosKernels_SOURCE_DIR_OVERRIDE:STRING=kokkos-kernels \
$TRILINOS_DIR
```

(Reproducer of the configuration is copy+paste from the failed job, some options will be unnecessary to enable to reproduce)

**Comment by ndellingwood** [comment]
Fixed by #1953
