### PR TITLE
Fix GitHub CI failing on broken `develop`

### PR DESCRIPTION
**Pull request by mzuzek**
@lucbv @crtrott @kliegeois 

This PR addresses couple of issues that cause GitHub CI to fail with _unrelated_ compilation errors (i.e. broken `develop`):
* Kokkos updates:
  - [x] [PR#5135](https://github.com/kokkos/kokkos/pull/5135) deprecates `Kokkos::InitArguments` replacing it with new `Kokkos::InitializationSettings`: here we update Kokkos initialization in performance tests accordingly;
    - **Note:** Deprecated `num_numa` was being set in [_perf_test/sparse/KokkosSparse_block_pcg.cpp_](https://github.com/kokkos/kokkos-kernels/pull/1461/files#diff-1d9913f65a6408f50d3d5bf03674cddfa41b08594efa5afd48baf7d6e2ea2146L380).
  - [x] [PR#5178](https://github.com/kokkos/kokkos/pull/5178) guards against private header inclusion: here we switch to _Kokkos_StdAlgorithms.hpp_ for std algorithms and just drop other private includes (like  _Kokkos_Concepts.hpp_);
  - [x] [PR#5144](https://github.com/kokkos/kokkos/pull/5144) removes `static` from execution space `print_configuration()`: we call it on instances now;
* Bugs:
  - [x] Bug in batched GESV (introduced by #1384) and detected with `Kokkos_ENABLE_DEBUG_BOUNDS_CHECK=ON` introduced by #1411 - see [the details below](https://github.com/kokkos/kokkos-kernels/pull/1461#issuecomment-1182232042);

### CODE REVIEW

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pre-Test Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           NO INSPECTION HAS BEEN PERFORMED ON THIS PULL REQUEST! - This PR must be inspected by setting label 'AT: PRE-TEST INSPECTED'.

**Review by lucbv — APPROVED** [review]
Looks good to me, thanks for updating the tests @mzuzek

**Review by lucbv — APPROVED** [review]
Thanks for the additional clean-up

**Comment by mzuzek** [comment]
### GESV bug details

@lucbv @kliegeois
In batched GESV (e.g. [_KokkosBatched_Gesv_Impl.hpp_:553](https://github.com/kokkos/kokkos-kernels/blob/838ab1fd4da7bf9aae1f6440e9d0a17f81e0a668/src/batched/dense/impl/KokkosBatched_Gesv_Impl.hpp#L553)) 2D temp views are created with `n`x`n+4` extents:
```cpp
ScratchPadMatrixViewType tmp(member.team_scratch(0), n, n + 4);
```
Because input matrix layout was enforced on `ScratchPadMatrixViewType` (e.g. see [lines 546-549](https://github.com/kokkos/kokkos-kernels/blob/838ab1fd4da7bf9aae1f6440e9d0a17f81e0a668/src/batched/dense/impl/KokkosBatched_Gesv_Impl.hpp#L546-L549)), when the input was a `subview` created in dense unit tests, `ScratchPadMatrixViewType` had `LayoutStride` and `n + 4` was passed by `View` constructor to [`LayoutStride` constructor](https://kokkos.github.io/kokkos-core-wiki/API/core/view/layoutStride.html#constructors) as a _stride_ instead of second _extent_, like with regular layouts (I'd say it's a bit of a trap there in multidimensional `Kokkos::View` constructor...). Because in batched test `tmp` ended up being `n` x 1 rank-1 view instead of intended `n` x `n+4` rank-2 view, when trying to split `tmp` into `PDAD`, `PDY`, `D2`, etc. with `subview` in [_KokkosBatched_Gesv_Impl.hpp_:554-558](https://github.com/kokkos/kokkos-kernels/blob/838ab1fd4da7bf9aae1f6440e9d0a17f81e0a668/src/batched/dense/impl/KokkosBatched_Gesv_Impl.hpp#L554-L558) we got [bounds violation errors](https://github.com/kokkos/kokkos-kernels/runs/7293894427?check_suite_focus=true#step:8:580) in CI here:
```shell
[ RUN      ] serial.batched_scalar_team_gesv_static_pivoting_float
unknown file: Failure
C++ exception with description "Kokkos::subview bounds error ( Kokkos::ALL , 1 <= 3 - 0 )" thrown in the test body.
[  FAILED  ] serial.batched_scalar_team_gesv_static_pivoting_float (1 ms)
```
#### Solution

The fix proposed here allows `tmp` view to use default scratchpad layout - in hope it won't be `LayoutStride` - instead of imposing the one derived from input matrix.

It's hard for me to tell how this fix can affect the performance of GESV calculation based on `PDAD`, `PDY`, `D2`, etc. with regard to the underlying layout of these helper structures - so if that matters, please check that within your review, if possible.

**Comment by mzuzek** [comment]
@lucbv
Thank you for your reviews!
Hopefully, you can tolerate me piling up different fixes under one PR here... I can split them into separate PRs anytime, if you wish.

**Comment by kliegeois** [comment]
Thanks @mzuzek for having found the issue! I am wondering if we should revisit the template arguments of the GESV to allow the users to specify the layout of the temporary view.

**Review by lucbv — APPROVED** [review]
Yep, this should do it, thanks for all the fixes

**Comment by lucbv** [comment]
@mzuzek actually we need to keep all these fixes in a single PR otherwise the auto-tester would keep on failing since we test against the develop branch of Kokkos Core.

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pre-Test Inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED by label AT: PRE-TEST INSPECTED! Autotester is Removing Label; This inspection will remain valid until a new commit to source branch is performed.

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_Tpls_CUDA9_GCC720_Light_Tpls_GCC720_GCC740</h3>
<ul>
  <li>Build Num: 294</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>fix-kokkos-initargs</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/NexGenAnalytics/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>0060bcd8d02672bf486861807fe385614bad7e8a</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>838ab1fd4da7bf9aae1f6440e9d0a17f81e0a668</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1461</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_Tpls_CUDA10_Tpls_CUDA10_LayoutRight</h3>
<ul>
  <li>Build Num: 287</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>fix-kokkos-initargs</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/NexGenAnalytics/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>0060bcd8d02672bf486861807fe385614bad7e8a</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>838ab1fd4da7bf9aae1f6440e9d0a17f81e0a668</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1461</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_GCC720</h3>
<ul>
  <li>Build Num: 1103</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>fix-kokkos-initargs</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/NexGenAnalytics/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>0060bcd8d02672bf486861807fe385614bad7e8a</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>838ab1fd4da7bf9aae1f6440e9d0a17f81e0a668</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1461</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_GCC720_Light_LayoutRight</h3>
<ul>
  <li>Build Num: 747</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>fix-kokkos-initargs</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/NexGenAnalytics/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>0060bcd8d02672bf486861807fe385614bad7e8a</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>838ab1fd4da7bf9aae1f6440e9d0a17f81e0a668</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1461</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_Tpls_GCC720</h3>
<ul>
  <li>Build Num: 1091</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>fix-kokkos-initargs</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/NexGenAnalytics/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>0060bcd8d02672bf486861807fe385614bad7e8a</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>838ab1fd4da7bf9aae1f6440e9d0a17f81e0a668</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1461</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_Tpls_INTEL18</h3>
<ul>
  <li>Build Num: 1078</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>fix-kokkos-initargs</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/NexGenAnalytics/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>0060bcd8d02672bf486861807fe385614bad7e8a</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>838ab1fd4da7bf9aae1f6440e9d0a17f81e0a668</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1461</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: KokkosKernels_PullRequest_CLANG1001</h3>
<ul>
  <li>Build Num: 483</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_BRANCH</td>
    <td>fix-kokkos-initargs</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_REPO</td>
    <td>https://github.com/NexGenAnalytics/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_SOURCE_SHA</td>
    <td>0060bcd8d02672bf486861807fe385614bad7e8a</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_REPO</td>
    <td>https://github.com/kokkos/kokkos-kernels</td>
  </tr>

  <tr>
    <td>KOKKOSKERNELS_TARGET_SHA</td>
    <td>838ab1fd4da7bf9aae1f6440e9d0a17f81e0a668</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>1461</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>KOKKOSKERNELS</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: KOKKOSKERNELS (NexGenAnalytics/kokkos-kernels)</dt>
  <ul>
    <li>Branch: fix-kokkos-initargs</li>
    <li>SHA: 0060bcd8d02672bf486861807fe385614bad7e8a</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: mzuzek
</details>

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pre-Merge Inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ lucbv ]!

**Comment by kokkos-devops-admin** [comment]
Status Flag 'Pull Request AutoTester' - Pull Request MUST BE MERGED MANUALLY BY Project Team - This Repo does not support Automerge

**Comment by e10harvey** [comment]
Thank you, @mzuzek !
