### PR TITLE
Explicitly include Kokkos_Half.hpp when using Kokkos::Experimental::[b]half_t

### PR DESCRIPTION
**Pull request by masterleinad**
Fixes https://my.cdash.org/builds/3680847/build by including the `Kokkos_Half.hpp` in all source files that don't include `Kokkos_Core.hpp` already.

### CODE REVIEW

**Review by lucbv — APPROVED** [review]

**Comment by ndellingwood** [comment]
Compilation errors like:

```
 /home/runner/_work/kokkos-kernels/kokkos-kernels/kokkos/install/include/Cuda/Kokkos_Cuda_Half_Conversion.hpp(16): error: function "Kokkos::Experimental::cast_to_half(float)" has already been defined (previous definition at line 936 of /home/runner/_work/kokkos-kernels/kokkos-kernels/kokkos/install/include/impl/Kokkos_Half_FloatingPointWrapper.hpp)
  half_t cast_to_half(half_t val) { return val; }
         ^

/home/runner/_work/kokkos-kernels/kokkos-kernels/kokkos/install/include/Cuda/Kokkos_Cuda_Half_Conversion.hpp(19): error: function "Kokkos::Experimental::cast_to_half(float)" has already been defined (previous definition at line 936 of /home/runner/_work/kokkos-kernels/kokkos-kernels/kokkos/install/include/impl/Kokkos_Half_FloatingPointWrapper.hpp)
  half_t cast_to_half(float val) { return __float2half(val); }
...
```

kokkos-kernels CI  tests against the most recent kokkos release (5.1.1 here) rather than develop, are some changes needed for backward compatibility?

**Comment by masterleinad** [comment]
> kokkos-kernels CI tests against the most recent kokkos release (5.1.1 here) rather than develop, are some changes needed for backward compatibility?

Ah, that makes sense. Let me fix that real quick.

**Comment by masterleinad** [comment]
I just added a version guard now.

File: common/src/KokkosKernels_ArithTraits.hpp [hunk 1]
```diff
@@ -21,10 +21,14 @@
 /// \brief Declaration and definition of KokkosKernels::ArithTraits
 
 #include <KokkosKernels_config.h>
+
+#include <Kokkos_Macros.hpp>
+#if KOKKOS_VERSION_GREATER_EQUAL(5, 1, 1)
```
Comment (lucbv) [inline common/src/KokkosKernels_ArithTraits.hpp]: Should it be strictly greater than 5.1.1 or will it work with 5.1.1 already?

Comment (masterleinad) [inline common/src/KokkosKernels_ArithTraits.hpp]:
```suggestion
#if KOKKOS_VERSION_GREATER(5, 1, 1)
```

File: sparse/src/KokkosSparse_IOUtils.hpp [hunk 2]
```diff
@@ -7,6 +7,11 @@
 #include "KokkosSparse_CrsMatrix.hpp"
 #include "KokkosSparse_SellMatrix.hpp"
 
+#include <Kokkos_Macros.hpp>
+#if KOKKOS_VERSION_GREATER_EQUAL(5, 1, 1)
```
Comment (masterleinad) [inline sparse/src/KokkosSparse_IOUtils.hpp]:
```suggestion
#if KOKKOS_VERSION_GREATER(5, 1, 1)
```

File: common/src/KokkosKernels_ArithTraits.hpp (hunk 1 above)
Comment (masterleinad) [reply common/src/KokkosKernels_ArithTraits.hpp]: Yes, it should be past 5.1.1.

**Review by lucbv — APPROVED** [review]
