### ISSUE TITLE
Link errors building KokkosSparse_gs.exe perf test

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#527]
With the kokkos-kernels develop branch I'm unable to build the gauss-seidel performance test `KokkosSparse_gs.cpp` due to link errors:

<details>
 <summary>LinkErrors</summary>

```
g++  KokkosSparse_gs.o -L/Users/ndellin/Research/kokkos_items/kokkos-kernels/testing/ETILinkError/install/lib -L./ -lkokkos_kernels -lkokkos -    ldl -lpthread -L/Users/ndellin/Research/kokkos_items/kokkos-kernels/testing/ETILinkError/kokkos/install/lib -fopenmp   -o KokkosSparse_gs.exe
Undefined symbols for architecture x86_64:
  "KokkosSparse::Impl::GAUSS_SEIDEL_APPLY<KokkosKernels::Experimental::KokkosKernelsHandle<unsigned long const, int const, double const, Kokkos:: OpenMP, Kokkos::HostSpace, Kokkos::HostSpace>, Kokkos::View<unsigned long const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::     HostSpace>, Kokkos::MemoryTraits<1u> >, Kokkos::View<int const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::  MemoryTraits<1u> >, Kokkos::View<double const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u>   >, Kokkos::View<double**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u> >, Kokkos::View<double  const**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u> >, false, false>::                       gauss_seidel_apply(KokkosKernels::Experimental::KokkosKernelsHandle<unsigned long const, int const, double const, Kokkos::OpenMP, Kokkos::        HostSpace, Kokkos::HostSpace>*, int, int, Kokkos::View<unsigned long const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::          HostSpace>, Kokkos::MemoryTraits<1u> >, Kokkos::View<int const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::  MemoryTraits<1u> >, Kokkos::View<double const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u>   >, Kokkos::View<double**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u> >, Kokkos::View<double  const**, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u> >, bool, bool, double, int, bool,        bool)", referenced from:
      void KokkosSparse::Experimental::symmetric_gauss_seidel_apply<KokkosKernels::Experimental::KokkosKernelsHandle<unsigned long, int, double,  Kokkos::OpenMP, Kokkos::HostSpace, Kokkos::HostSpace>, Kokkos::View<unsigned long const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP,      Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >, Kokkos::View<int*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >, Kokkos::View<double*, Kokkos::LayoutRight, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, void>, Kokkos::View<double*,    Kokkos::LayoutRight, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >, Kokkos::View<double*, Kokkos::LayoutRight,    Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> > >(KokkosKernels::Experimental::KokkosKernelsHandle<unsigned long,   int, double, Kokkos::OpenMP, Kokkos::HostSpace, Kokkos::HostSpace>*, KokkosKernels::Experimental::KokkosKernelsHandle<unsigned long, int, double, Kokkos::OpenMP, Kokkos::HostSpace, Kokkos::HostSpace>::const_nnz_lno_t, KokkosKernels::Experimental::KokkosKernelsHandle<unsigned long, int,      double, Kokkos::OpenMP, Kokkos::HostSpace, Kokkos::HostSpace>::const_nnz_lno_t, Kokkos::View<unsigned long const*, Kokkos::LayoutLeft, Kokkos::   Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >, Kokkos::View<int*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP,      Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >, Kokkos::View<double*, Kokkos::LayoutRight, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>,     void>, Kokkos::View<double*, Kokkos::LayoutRight, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >, Kokkos::         View<double*, Kokkos::LayoutRight, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >, bool, bool, KokkosKernels::     Experimental::KokkosKernelsHandle<unsigned long, int, double, Kokkos::OpenMP, Kokkos::HostSpace, Kokkos::HostSpace>::nnz_scalar_t, int) in        KokkosSparse_gs.o
  "KokkosSparse::Impl::GAUSS_SEIDEL_NUMERIC<KokkosKernels::Experimental::KokkosKernelsHandle<unsigned long const, int const, double const,        Kokkos::OpenMP, Kokkos::HostSpace, Kokkos::HostSpace>, Kokkos::View<unsigned long const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP,      Kokkos::HostSpace>, Kokkos::MemoryTraits<1u> >, Kokkos::View<int const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>,   Kokkos::MemoryTraits<1u> >, Kokkos::View<double const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::           MemoryTraits<1u> >, false, false>::gauss_seidel_numeric(KokkosKernels::Experimental::KokkosKernelsHandle<unsigned long const, int const, double   const, Kokkos::OpenMP, Kokkos::HostSpace, Kokkos::HostSpace>*, int, int, Kokkos::View<unsigned long const*, Kokkos::LayoutLeft, Kokkos::          Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u> >, Kokkos::View<int const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::       OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u> >, Kokkos::View<double const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::   HostSpace>, Kokkos::MemoryTraits<1u> >, bool)", referenced from:
      void KokkosSparse::Experimental::gauss_seidel_numeric<KokkosKernels::Experimental::KokkosKernelsHandle<unsigned long, int, double, Kokkos:: OpenMP, Kokkos::HostSpace, Kokkos::HostSpace>, Kokkos::View<unsigned long const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::     HostSpace>, Kokkos::MemoryTraits<0u> >, Kokkos::View<int*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::        MemoryTraits<0u> >, Kokkos::View<double*, Kokkos::LayoutRight, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, void> >(KokkosKernels::         Experimental::KokkosKernelsHandle<unsigned long, int, double, Kokkos::OpenMP, Kokkos::HostSpace, Kokkos::HostSpace>*, KokkosKernels::             Experimental::KokkosKernelsHandle<unsigned long, int, double, Kokkos::OpenMP, Kokkos::HostSpace, Kokkos::HostSpace>::const_nnz_lno_t,             KokkosKernels::Experimental::KokkosKernelsHandle<unsigned long, int, double, Kokkos::OpenMP, Kokkos::HostSpace, Kokkos::HostSpace>::              const_nnz_lno_t, Kokkos::View<unsigned long const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::               MemoryTraits<0u> >, Kokkos::View<int*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<0u> >, Kokkos::View<double*, Kokkos::LayoutRight, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, void>, bool) in KokkosSparse_gs.o
  "KokkosSparse::Impl::GAUSS_SEIDEL_SYMBOLIC<KokkosKernels::Experimental::KokkosKernelsHandle<unsigned long const, int const, double const,       Kokkos::OpenMP, Kokkos::HostSpace, Kokkos::HostSpace>, Kokkos::View<unsigned long const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP,      Kokkos::HostSpace>, Kokkos::MemoryTraits<1u> >, Kokkos::View<int const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>,   Kokkos::MemoryTraits<1u> >, false, false>::gauss_seidel_symbolic(KokkosKernels::Experimental::KokkosKernelsHandle<unsigned long const, int const, double const, Kokkos::OpenMP, Kokkos::HostSpace, Kokkos::HostSpace>*, int, int, Kokkos::View<unsigned long const*, Kokkos::LayoutLeft, Kokkos::   Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u> >, Kokkos::View<int const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::       OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u> >, bool)", referenced from:
      void runGS<unsigned long, int, Kokkos::OpenMP>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::       __cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool) in KokkosSparse_gs.o
  "KokkosSparse::Impl::SPMV<double const, int const, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u>, unsigned long   const, double const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<3u>, double*, Kokkos::          LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u>, false, false>::spmv(char const*, double const&,          KokkosSparse::CrsMatrix<double const, int const, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u>, unsigned long       const> const&, Kokkos::View<double const*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<3u> >      const&, double const&, Kokkos::View<double*, Kokkos::LayoutLeft, Kokkos::Device<Kokkos::OpenMP, Kokkos::HostSpace>, Kokkos::MemoryTraits<1u> >    const&)", referenced from:
      void runGS<unsigned long, int, Kokkos::OpenMP>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::       __cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool) in KokkosSparse_gs.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
```
</details>

develop branch SHA: 4cd9627e5bbe2bef8554c7bc6ea637bf849df2b8

OpenMP build with gcc/6.5 on my Mac laptop

Configuration:
```
KOKKOS_PATH=${HOME}/kokkos #path to kokkos source
KOKKOSKERNELS_SCALARS=double
KOKKOSKERNELS_LAYOUTS=LayoutLeft #the layout types to instantiate.
KOKKOSKERNELS_ORDINALS=int #ordinal types to instantiate
KOKKOSKERNELS_OFFSETS=int #offset types to instantiate
KOKKOSKERNELS_PATH=../.. #path to kokkos-kernels top directory.
KOKKOSKERNELS_OPTIONS=eti-only #options for kokkoskernels  
CXXFLAGS="-Wall -pedantic -Werror -O3 -g -Wshadow -Wsign-compare -Wignored-qualifiers -Wempty-body -Wclobbered -Wuninitialized"
CXX=g++ #${KOKKOS_PATH}/bin/nvcc_wrapper
KOKKOS_DEVICES=OpenMP #devices Cuda...

../../scripts/generate_makefile.bash --kokkoskernels-path=${KOKKOSKERNELS_PATH} --with-scalars=${KOKKOSKERNELS_SCALARS} --with-                   ordinals=${KOKKOSKERNELS_ORDINALS} --with-offsets=${KOKKOSKERNELS_OFFSETS} --kokkos-path=${KOKKOS_PATH} --with-devices=${KOKKOS_DEVICES} --       arch=${KOKKOS_ARCHS} --compiler=${CXX} --with-options=${KOKKOSKERNELS_OPTIONS}  --cxxflags="${CXXFLAGS}" --with-kokkos-                           options=${KOKKOS_OPTIONS} --with-layouts=${KOKKOSKERNELS_LAYOUTS}
```

**Comment by brian-kelley** [comment]
Fixed in #542.
