### PR TITLE
Implement Team and TeamVector Iamax

### PR DESCRIPTION
**Pull request by yasahi-hpc**
This PR aims at adding Team and TeamVector implementations of batched Iamax.

- [x] Adding `Team` and `TeamVector` implementations of batched Iamax
- [x] Add unit-tests for them
- [x] Integrate `Serial`, `Team` and `TeamVector` implementations in a single file

### CODE REVIEW

**Review by lucbv — APPROVED** [review]
Looks good to me, the files being renamed are impl only.
We should still try to limit these changes in general so we might want to design a developer guideline for this can of things.

**Comment by ndellingwood** [comment]
@lucbv @yasahi-hpc  I'm seeing some compilation errors in Trilinos integration tests with these updates, though it looks like they are directly in kokkos-kernels; this is from a Serial build with llvm/15.0.7, debug enabled, deprecated code 5 off (I'm not sure which specific option in this config triggers the error):

```
18:21:37 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug-new_view-dep_code5_off/Trilinos/kokkos-kernels/batched/dense/unit_test/backends/Test_Serial_Batched_Dense.cpp:7:
18:21:37 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug-new_view-dep_code5_off/Trilinos/kokkos-kernels/batched/dense/unit_test/Test_Batched_Dense.hpp:10:
18:21:37 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug-new_view-dep_code5_off/Trilinos/kokkos-kernels/batched/dense/unit_test/Test_Batched_Iamax.hpp:9:
18:21:37 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug-new_view-dep_code5_off/Trilinos/kokkos-kernels/batched/dense/src/KokkosBatched_Iamax.hpp:62:
18:21:37 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug-new_view-dep_code5_off/Trilinos/kokkos-kernels/batched/dense/impl/KokkosBatched_Iamax_Impl.hpp:11:
18:21:37 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug-new_view-dep_code5_off/Trilinos/kokkos-kernels/batched/dense/impl/KokkosBatched_Iamax_Internal.hpp:69:22: error: no matching constructor for initialization of 'reducer_value_type' (aka 'Kokkos::ValLocScalar<double, unsigned long>')
18:21:37   reducer_value_type max_first_loc(KokkosKernels::ArithTraits<mag_type>::zero(), 0);
18:21:37                      ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
18:21:37 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug-new_view-dep_code5_off/Trilinos/kokkos-kernels/batched/dense/impl/KokkosBatched_Iamax_Impl.hpp:35:47: note: in instantiation of function template specialization 'KokkosBatched::Impl::TeamIamaxInternal<Kokkos::Impl::HostThreadTeamMember<Kokkos::Serial>>::invoke<unsigned long, double>' requested here
18:21:37   return Impl::TeamIamaxInternal<MemberType>::invoke(member, static_cast<size_type>(x.extent(0)), x.data(),
18:21:37                                               ^
18:21:37 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug-new_view-dep_code5_off/Trilinos/kokkos-kernels/batched/dense/unit_test/Test_Batched_Iamax.hpp:34:78: note: in instantiation of function template specialization 'KokkosBatched::TeamIamax<Kokkos::Impl::HostThreadTeamMember<Kokkos::Serial>>::invoke<Kokkos::View<double *, Kokkos::LayoutStride, Kokkos::Device<Kokkos::Serial, Kokkos::HostSpace>, Kokkos::MemoryTraits<0>>>' requested here
18:21:37       iamax = static_cast<index_type>(KokkosBatched::TeamIamax<member_type>::invoke(member, sub_x));
18:21:37                                                                              ^
18:21:37 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug-new_view-dep_code5_off/Trilinos/kokkos/core/src/Serial/Kokkos_Serial_Parallel_Team.hpp:227:7: note: in instantiation of member function 'Test::Iamax::Functor_BatchedIamax<Kokkos::Serial, Kokkos::View<double **, Kokkos::LayoutLeft, Kokkos::Serial>, Kokkos::View<int *, Kokkos::LayoutLeft, Kokkos::Serial>, KokkosBlas::Mode::Team>::operator()' requested here
18:21:37       m_functor(Member(data, ileague, m_league));
18:21:37       ^
18:21:37 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug-new_view-dep_code5_off/Trilinos/kokkos/core/src/Serial/Kokkos_Serial_Parallel_Team.hpp:263:20: note: in instantiation of function template specialization 'Kokkos::Impl::ParallelFor<Test::Iamax::Functor_BatchedIamax<Kokkos::Serial, Kokkos::View<double **, Kokkos::LayoutLeft, Kokkos::Serial>, Kokkos::View<int *, Kokkos::LayoutLeft, Kokkos::Serial>, KokkosBlas::Mode::Team>, Kokkos::TeamPolicy<Kokkos::Serial>, Kokkos::Serial>::exec<void>' requested here
18:21:37     this->template exec<typename Policy::work_tag>(
18:21:37                    ^
18:21:37 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug-new_view-dep_code5_off/Trilinos/kokkos/core/src/Kokkos_Parallel.hpp:144:11: note: in instantiation of member function 'Kokkos::Impl::ParallelFor<Test::Iamax::Functor_BatchedIamax<Kokkos::Serial, Kokkos::View<double **, Kokkos::LayoutLeft, Kokkos::Serial>, Kokkos::View<int *, Kokkos::LayoutLeft, Kokkos::Serial>, KokkosBlas::Mode::Team>, Kokkos::TeamPolicy<Kokkos::Serial>, Kokkos::Serial>::execute' requested here
18:21:37   closure.execute();
18:21:37           ^
18:21:37 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug-new_view-dep_code5_off/Trilinos/kokkos-kernels/batched/dense/unit_test/Test_Batched_Iamax.hpp:52:13: note: in instantiation of function template specialization 'Kokkos::parallel_for<const char *, Kokkos::TeamPolicy<Kokkos::Serial>, Test::Iamax::Functor_BatchedIamax<Kokkos::Serial, Kokkos::View<double **, Kokkos::LayoutLeft, Kokkos::Serial>, Kokkos::View<int *, Kokkos::LayoutLeft, Kokkos::Serial>, KokkosBlas::Mode::Team>>' requested here
18:21:37     Kokkos::parallel_for(name.c_str(), policy, *this);
18:21:37             ^
18:21:37 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug-new_view-dep_code5_off/Trilinos/kokkos-kernels/batched/dense/unit_test/Test_Batched_Iamax.hpp:127:84: note: in instantiation of member function 'Test::Iamax::Functor_BatchedIamax<Kokkos::Serial, Kokkos::View<double **, Kokkos::LayoutLeft, Kokkos::Serial>, Kokkos::View<int *, Kokkos::LayoutLeft, Kokkos::Serial>, KokkosBlas::Mode::Team>::run' requested here
18:21:37   Functor_BatchedIamax<DeviceType, View2DType, MaxView1DType, ArgMode>(A0, iamax0).run();
18:21:37                                                                                    ^
18:21:37 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug-new_view-dep_code5_off/Trilinos/kokkos-kernels/batched/dense/unit_test/Test_Batched_Iamax.hpp:249:18: note: in instantiation of function template specialization 'Test::Iamax::impl_test_batched_iamax_analytical<Kokkos::Serial, double, Kokkos::LayoutLeft, KokkosBlas::Mode::Team>' requested here
18:21:37     Test::Iamax::impl_test_batched_iamax_analytical<DeviceType, ScalarType, LayoutType, ArgMode>(1);
18:21:37                  ^
18:21:37 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug-new_view-dep_code5_off/Trilinos/kokkos-kernels/batched/dense/unit_test/Test_Batched_Iamax.hpp:294:3: note: in instantiation of function template specialization 'test_batched_iamax<Kokkos::Serial, double, KokkosBlas::Mode::Team>' requested here
18:21:37   test_batched_iamax<TestDevice, double, KokkosBatched::Mode::Team>();
18:21:37   ^
18:21:37 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug-new_view-dep_code5_off/Trilinos/kokkos/core/src/impl/Kokkos_BuiltinReducers.hpp:288:8: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
18:21:37 struct ValLocScalar {
18:21:37        ^
18:21:37 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug-new_view-dep_code5_off/Trilinos/kokkos/core/src/impl/Kokkos_BuiltinReducers.hpp:288:8: note: candidate constructor (the implicit move constructor) not viable: requires 1 argument, but 2 were provided
18:21:37 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_LLVM1507_Serial_debug-new_view-dep_code5_off/Trilinos/kokkos/core/src/impl/Kokkos_BuiltinReducers.hpp:288:8: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 2 were provided
```

**Comment by yasahi-hpc** [comment]
Thank you for reporting @ndellingwood 
Can you try this https://github.com/kokkos/kokkos-kernels/pull/3145
