### ISSUE TITLE
Nightly build failures with rocm/5.2.0 and rocsparse TPL

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#1715]
Nightly Hip builds with rocm/5.2.0 and the rocsparse tpl enabled began failing following changes in #1701 with error message:

```
05:18:44 /home/jenkins/caraway-new/workspace/KokkosKernels_CarawayMI100_Rocm520_HipSerial_RocBlas_RocSparse/kokkos-kernels/sparse/tpls/KokkosSparse_spmv_tpl_spec_decl.hpp:439:35: error: use of undeclared identifier 'rocsparse_spmv_ex'
05:18:44   KOKKOS_ROCSPARSE_SAFE_CALL_IMPL(rocsparse_spmv_ex(
```

**Reproducer** (caraway M100 queue):
```bash
module load cmake/3.19.3 rocm/5.2.0

$KOKKOSKERNELS_PATH/cm_generate_makefile.bash --with-devices=Hip,Serial --arch=VEGA908 --compiler=hipcc --cxxflags="-O3  " --cxxstandard="17" --ldflags=""  --with-hip --kokkos-path=$KOKKOS_PATH --kokkoskernels-path=$KOKKOSKERNELS_PATH --with-scalars='double,complex_double' --with-ordinals=int --with-offsets=int,size_t --with-layouts=LayoutLeft --with-tpls=rocblas,rocsparse  --no-examples
```

@cwpearson can you investigate?

Edit: Adding link to nightly failure: https://jenkins-son.sandia.gov/job/KokkosKernels_CarawayMI100_Rocm520_HipSerial_RocBlas_RocSparse/97

**Comment by ndellingwood** [comment]
I think I see the issue, will put in a PR with a fix

**Comment by ndellingwood** [comment]
PR #1716 opened which should resolve the issue

**Comment by cwpearson** [comment]
This was introduced by my sloppy fix for https://github.com/kokkos/kokkos-kernels/issues/1700.

**Comment by cwpearson** [comment]
Appears to be fixed in https://github.com/kokkos/kokkos-kernels/pull/1716
